### ISSUE TITLE
`terraform fmt` repeatedly indents some multiline comments

### ISSUE THREAD

**Issue by michaelkaye** [hashicorp/terraform#10286]
### Terraform Version
Terraform v0.7.11

### Affected Resource(s)
None.

### Terraform Configuration Files
```hcl
resource "aws_security_group" "test" {
  /*ingress {
    protocol = "tcp"
    from_port = 80
    to_port = 80
    cidr_blocks = ["127.0.0.1/32"]
  }*/
}
```

### Debug Output

https://gist.github.com/michaelkaye/6b9ee87e9a610e69f6061572ab034344

### Expected Behavior
One run of `terraform fmt` should format the file, repeated runs on a formatted file should not keep changing it.

### Actual Behavior
Each run of `terraform fmt` indents the contents of the comment block by an additional 2 spaces.

### Steps to Reproduce
1. `terraform fmt` (multiple times on the same file, such as an a automated linting script or commit checker should do)

### References
https://github.com/hashicorp/terraform/issues/9859 - possibly a similar issue with multi-line strings

**Comment by mitchellh** [comment]
This is fixed in 0.8, try the beta!

**Comment by mihir3535** [comment]
This problem seems to still exist for other kinds of multiline comments on Terraform 0.8.8:

![example](https://cloud.githubusercontent.com/assets/5190697/23580844/44126bb4-00d7-11e7-98f0-dd4728ff96f1.gif)

In this example, I have an Atom plugin to run `terraform fmt` on every save.
