### ISSUE TITLE
terraform should gracefully quit on SIGTERM

### ISSUE THREAD

**Issue by mildred** [hashicorp/terraform#10459]
Terraform Version: 0.7.5-132-g7e04082

Looking at code, it seems that terraform gracefully shuts down on `SIGINT` (`os.Terminate` in go) but does not respond to `SIGTERM` (`syscall.SIGTERM`). The first signal is used when interrupting from command line (Ctrl-C0 while the latter is used when using the `kill` command.

I am using terraform unattended in a system service, and systemd generally uses `SIGTERM` to notify a service to stop. It can be reconfigured to use `SIGINT` but it would be nice if terraform could make use of `SIGTERM`.

**Comment by mitchellh** [comment]
I agree.

For impl notes (maybe me): we'll need to use conditional build files here since syscall.SIGTERM isn't available on Windows, I believe.

**Comment by mildred** [comment]
Probably, panicwrap will need to be changed as well

https://github.com/mitchellh/panicwrap/blob/master/panicwrap.go#L170

**Comment by mildred** [comment]
I have the master branch here modified to make it work. Still WIP https://github.com/squarescale/terraform

**Comment by mitchellh** [comment]
Done!

**Comment by mildred** [comment]
@mitchellh you merged part of the solution only. there is still a problem with panicwrap. it ignores the SIGTERM signal instead of forwarding it to the main process. Contrary to SIGINT, SIGTERM is generally sent only to the parent process, so ignoring it in panicwrap is not a guarantee that it will reach the main process.

On some circumstances (using killall or systemd where it kill the complete cgroup, this is configurable) this will work. on some other setups (running inside docker for instance) this will fail.

That's why I think that panicwrap should be modified to allow forwarding some signals.

Also, I was just thinking that forwarding the SIGTERM signal could cause it to be received twice on the main process, forcing the shutdown instead of keeping graceful. In that circumstance, I think SIGTERM should not trigger a force shutdown when received more than once. here are the two use cases:

1. where the signal is sent to the parent process only (docker, ...):

* terraform starts
* SIGTERM is sent to the parent process (panicwrap)
* panicwrap forwards the SIGTERM signal to the main process
* the mainprocess received SIGTERM only once, it gracefully shuts down
* to force shutdown, SIGINT could be used on the main process

2. where the signals is sent to all processes of the control group, or through killall:

* terraform starts
* SIGTERM is sent to all processes, including the panicwrap process and the main process
* panicwrap forwards the SIGTERM signal to the main process
* the mainprocess received SIGTERM twice, it ignores the second occurence and gracefully shuts down
* to force shutdown, SIGINT could be used on the main process

Do you think this could be a good way to implement it ?

**Comment by mitchellh** [comment]
Yes I understand that I will merge in your panicwrap fix. Unfortunately I can't reopen the PR for whatever reason so I'll have to just move the diffs over.
