### ISSUE TITLE
${file()} interpolation problems

### ISSUE THREAD

**Issue by tonglil** [hashicorp/terraform#10510]
I think this may be related to the conversation near the end of https://github.com/hashicorp/terraform/issues/9308.

https://github.com/hashicorp/terraform/issues/10059

### Terraform Version
```
terraform -v
Terraform v0.7.13
```

### Affected Resource(s)
- aws_instance

### Terraform Configuration Files
```hcl
resource "aws_instance" "web" {
  ami = "ami-xxxx"
  instance_type = "t2.nano"
  key_name = "${lookup(var.key_name, var.environment_name)}"
  subnet_id = "${element(split(",", lookup(var.ops_subnets, var.environment_name)), 1)}"

  ...

  tags {
    App = "${var.app_name}"
    Environment = "${var.environment_name}"
  }

  # Bootstrap the VM
  provisioner "remote-exec" {
    inline = [
      "git clone some-url",
      "sudo /usr/local/bin/some-script"
    ]
    connection {
      type = "ssh"
      host = "${self.private_ip}"
      user = "centos"
      agent = false
      private_key = "${file("~/.ssh/key-${var.environment_name}.pem")}"
    }
  }
```

### Debug Output
https://gist.github.com/tonglil/f3360ded5ac7a53e8e353ae905893356

### Expected Behavior
Success

### Actual Behavior
Failure
```
Error applying plan:

1 error(s) occurred:

* file: exec: "getent": executable file not found in $PATH in:

${file("~/.ssh/app-${var.environment_name}.pem")}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Nothing special.

### References
This is where I see TF could be calling `getent`: https://github.com/mitchellh/go-homedir/pull/8/files.

It seems like TF is trying to run ON the machine? I can't tell because I'm on OS X and I don't have `getent` installed.

The `~/.ssh/app-stg.pem` file does exists on my local machine:
```
ls -la ~/.ssh/
total 64K
drwx------  15 207383 1490099278  510 Oct 25 18:36 ./
drwxr-xr-x+ 89 207383 staff      3.0K Dec  2 12:35 ../
-rw-------   1 207383 1490099278  417 Jun 10 14:59 config
-rw-------   1 207383 1490099278 3.3K Aug 18 13:19 id_rsa
-rw-r--r--   1 207383 1490099278  745 Jun  7 15:35 id_rsa.pub
-rw-------   1 207383 1490099278 8.9K Dec  2 15:08 known_hosts
-rw-------   1 207383 1490099278 1.7K Jun  8 17:38 app-dev.pem
-rw-------   1 207383 1490099278 1.7K Jun  8 17:38 app-prd.pem
-rw-------   1 207383 1490099278 1.7K Jun  8 17:38 app-stg.pem
```

The variable is getting interpolated everywhere else, as shown by the plan, and the [instance TAGs](https://gist.github.com/tonglil/f3360ded5ac7a53e8e353ae905893356#file-output-L48) are applied to the instance (I can see that in the AWS console).

**Comment by mitchellh** [comment]
Ah, you found a bug in homedir that I just updated. It should fall back and try another method.

But yes, that file() method will run on the machine running Terraform!

**Comment by tonglil** [comment]
Thanks, does this mean I should wait for the next release of TF?

**Comment by mitchellh** [comment]
Yep, the error should be fixed in the next version. 0.8 final should come out this week barring any horrendous issues reported.

**Comment by tonglil** [comment]
Sorry to say, but I am still getting the same error with Terraform `v0.8.1`.

```
$ echo $HOME
/Users/207383
$ pwd
/Users/207383/.ssh
$ ls -la ~/.ssh/
total 64K
drwx------  15 207383 1490099278  510 Oct 25 18:36 ./
drwxr-xr-x+ 89 207383 staff      3.0K Dec  2 12:35 ../
-rw-------   1 207383 1490099278  417 Jun 10 14:59 config
-rw-------   1 207383 1490099278 3.3K Aug 18 13:19 id_rsa
-rw-r--r--   1 207383 1490099278  745 Jun  7 15:35 id_rsa.pub
-rw-------   1 207383 1490099278 8.9K Dec  2 15:08 known_hosts
-rw-------   1 207383 1490099278 1.7K Jun  8 17:38 app-dev.pem
-rw-------   1 207383 1490099278 1.7K Jun  8 17:38 app-prd.pem
-rw-------   1 207383 1490099278 1.7K Jun  8 17:38 app-stg.pem
```

Based on https://github.com/mitchellh/go-homedir/pull/8/files#diff-de00ee27499a6e734e559cc2aa35a70aR81, it shouldn't try to call `getent` since my `$HOME` is set. I don't have `getent` installed on my computer.
