### ISSUE TITLE
Error from provider defined in module "unknown variable accessed: var.access_key", TF 0.8.0

### ISSUE THREAD

**Issue by ljfranklin** [hashicorp/terraform#10711]
### Terraform Version
Error under Terraform v0.8.0, worked as expected under v0.7.13

### Affected Resource(s)
Appears when defining a provider inside a module. Works as expected if provider is defined outside the module.

### Terraform Configuration Files

fixtures/module/module.tf
```hcl
variable "access_key" {}
variable "secret_key" {}
variable "region" {
    default = "us-east-1"
}
variable "bucket" {}

module "test_module" {
  source = "../aws"

  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.region}"

  bucket = "${var.bucket}"
}
```

fixtures/aws/example.tf
```hcl
variable "access_key" {}
variable "secret_key" {}
variable "region" {
    default = "us-east-1"
}
variable "bucket" {}

provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region     = "${var.region}"
}

resource "aws_s3_bucket_object" "s3_object" {
  bucket     = "${var.bucket}"
  key        = "foo"
  content    = "foo"
}
```

### Debug Output

When running apply or plan, it returns the following error (sometimes says secret_key is unknown instead):
```
Error running plan: 1 error(s) occurred:

* 1:3: unknown variable accessed: var.access_key in:

${var.access_key}
```

Debug output from 0.8.0 (busted): https://gist.github.com/ljfranklin/9a22219aea0097047e187456680cce61
Debug output from 0.7.13 (working): https://gist.github.com/ljfranklin/4da85c6c60d13119a9437ceb430b9eb5

### Expected Behavior
Expected plan or apply to succeed against the above module: `terraform plan fixtures/module/`. This worked as expected under v0.7.13. 

### Actual Behavior
Terraform returns the above error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create the two files listed above.
1. `terraform plan fixtures/module/`
1. Verify "unknown variable accessed" error appears

### Important Factoids
If provider is defined in `module.tf` rather than inside the module source (`example.tf`) then the plan succeeds as expected.

**Comment by mitchellh** [comment]
Reproduced, working on it. In the mean time, you can workaround it by specifying `-Xlegacy-graph` on the CLI.

**Comment by mitchellh** [comment]
Fix is in reference PR, will be fixed in 0.8.1. Thank you!

**Comment by mitchellh** [comment]
I want to note that this only happens if a module variable is used _only_ by a provider. If it is also referenced by anything else (output, resource) then this works. This can be used by a workaround if `-Xlegacy-graph` can't be used since you're using new TF 0.8 features.

**Comment by ashvini** [comment]
I am also facing same issue with terraform 08.what is the workaround?

Regards,
Ashwini

**Comment by mitchellh** [comment]
This is fixed in 0.8.1 which we just released!

**Comment by mcanevet** [comment]
@mitchellh I think this is only partially fixed as I can see `unknown variable accessed` messages when applying one resource using `-target`

**Comment by bradleythughes** [comment]
@mcanevet This was also reported here: #10911
