### ISSUE TITLE
provider/google incorrect update order between instance template and group manager

### ISSUE THREAD

**Issue by lobeck** [hashicorp/terraform#11905]
### Terraform Version
Terraform v0.8.6

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance_template
- google_compute_instance_group_manager

### Terraform Configuration Files
```hcl
resource "google_compute_instance_template" "consul" {
  count = "${length(var.regions)}" # one per region
  name_prefix = "${var.name}-${element(var.regions, count.index)}-"
  tags = "${concat(var.tags, list(join("-", list(var.nat_tag, element(var.regions, count.index)))), list("consul"))}"

  region = "${element(var.regions, count.index)}"

  description = "${var.description}"
  machine_type = "${var.machine_type}"

  # Create a new boot disk from an image
  disk {
    source_image = "$foo-ubuntu-1204-precise" # it's a family name
    disk_type = "${var.disk_type}"
  }

  network_interface {
    network = "${var.network}"
  }

  service_account {
    scopes = ["storage-ro", "compute-ro"]
  }

  metadata {
    startup-script-url = "${var.default_startup_script}"
  }

  lifecycle {
    create_before_destroy = true
  }

resource "google_compute_instance_group_manager" "consul" {
  count = "${length(var.regions)}" # one per region
  zone = "${element(var.regions, count.index)}-${element(var.zones[element(var.regions, count.index)], (count.index) / length(var.regions))}"
  name = "${var.name}-${element(var.regions, count.index)}"
  update_strategy    = "NONE"

  target_size  = "${var.count}"

  base_instance_name = "${var.name}-${element(var.regions, count.index)}"

  instance_template  = "${element(google_compute_instance_template.consul.*.self_link, count.index)}"

}
```
### Terraform plan
```
~ module.infrastructure.consul.google_compute_instance_group_manager.consul.0
    instance_template: "https://www.googleapis.com/compute/v1/projects/$project/global/instanceTemplates/consul-europe-west1" => "https://www.googleapis.com/compute/v1/projects/$project/global/instanceTemplates/consul-europe-west1-001e39d3e89692fb74c75a96e8"

~ module.infrastructure.consul.google_compute_instance_group_manager.consul.1
    instance_template: "https://www.googleapis.com/compute/v1/projects/$project/global/instanceTemplates/consul-us-east1" => "https://www.googleapis.com/compute/v1/projects/$project/global/instanceTemplates/consul-us-east1-001e39d3e89692fb74c75a96e7"

- module.infrastructure.consul.google_compute_instance_template.consul.0 (deposed)

- module.infrastructure.consul.google_compute_instance_template.consul.1 (deposed)
```

### Expected Behavior
The group_manager gets updated to use the new template, then the old template gets deleted

### Actual Behavior
It tries to delete the template first, which subsequently fails with `google_compute_instance_template.consul.0 (deposed #0): Error deleting instance template: googleapi: Error 400: The instance_template resource 'consul-europe-west1-001e39d3e89692fb74c75a96e8' is already being used by 'consul-europe-west1', resourceInUseByAnotherResource`

### Steps to Reproduce
- Setup everything
- Update the image/add a new image (family lookup has no effect, so i'm specifying the exact versions)
- plan works but apply fails due to the incorrect order.

**Comment by lobeck** [comment]
It seems as this is an issue with `instance_template  = "${element(google_compute_instance_template.consul.*.self_link, count.index)}"`, as it works when self_link is directly used (without the `element()` call)

Any ideas how to fix this?

**Comment by andyshinn** [comment]
I think it is still an issue even without `element()`. I am getting the error with a regular `self_link` attribute.

**Comment by OmarDarwish** [comment]
I am also still running into this issue with v0.11.10

**Comment by OmarDarwish** [comment]
Resolved by https://github.com/terraform-providers/terraform-provider-google/issues/1601:

* Add to `google_compute_instance_template` 
```
lifecycle {
  create_before_destroy = true
}
``` 
* Change `name` attribute to something other than what the existing template is named
* `terraform apply`
* (Optional) Change name back to what it was originally
* `terraform apply`

**Comment by universalvishwa** [comment]
This issue is still there in _Terraform v0.11.10_. I tried all the possible options stated above. Additionally What I want to add is, After the failure, when I re-run the 'terraform apply' for the second it successfully passed. My guess is that, Terarform is trying to destroy the old resource a little too quicker, before the Google's API is gets updated with then new instance template. If the destruction of the 'create_before_destroy' can be delayed by few seconds, this might work.

**Comment by ralvarez-uy** [comment]
In my case, the instances (created by the mig) do not get updated (at least quickly enough) thus leaving an explicit dependency with the old template (and so it's unable to be deleted since it's in use by other element).

**Comment by keedon** [comment]
I'm also seeing this problem with terraform 0.11.13 and provider.google v2.11.0
