### ISSUE TITLE
Empty network name forcing google_compute_instance recreation

### ISSUE THREAD

**Issue by ndarilek** [hashicorp/terraform#1286]
Seeing this on latest master + a couple of my PRs. Here is the relevant portion of my config:

  network_interface {
    network = "${google_compute_network.default.name}"
    access_config {
      nat_ip = "${element(google_compute_address.default.*.address, count.index)}"
    }
  }

I create the instance and immediately run `terraform plan -no-color`. This gives me

bash-3.1$ terraform plan -no-color |grep force
    network_interface.0.network:                "" => "default" (forces new resource)

Any idea why the network name is getting read as an empty string?

**Comment by sparkprime** [comment]
I think this should be fixed in master.

**Comment by ndarilek** [comment]
Has this fix not landed in 0.5? I'm still seeing it. Or is there some change I can make to my state file? I don't want to have to recreate the entire resource if I don't have to.

**Comment by sparkprime** [comment]
The fix should be in.  I just tried the following and the plan was empty after deployment:

    resource "google_compute_network" "mynetwork" {
        name = "mynetwork"
        ipv4_range = "10.0.0.0/24"
    }
    
    resource "google_compute_address" "myaddress" {
        name = "myaddress-${count.index}"
        count = 3
    }
    
    resource "google_compute_instance" "myinstance" {
        name = "myinstance-${count.index}"
        count = 3
        machine_type = "n1-standard-1"
        zone = "us-central1-a"
        disk {
            image = "debian-7-wheezy-v20140814"
        }
        network_interface {
            network = "${google_compute_network.mynetwork.name}"
            access_config {
                nat_ip = "${element(google_compute_address.myaddress.*.address, count.index)}"
            }
        }
    }

Can you verify that it works for you with fresh instance?  If a previous bug has left your tfstate in a corrupted state, I'm sure there's a way to surgically heal it to avoid you having to redeploy instances.
