### ISSUE TITLE
SSM Document updates not working

### ISSUE THREAD

**Issue by awuetz** [hashicorp/terraform#13976]
Hi *,

i noticed some issues with the resource aws_ssm_document if you do updates on the tf config or within the AWS console.

I think the resolution could be the same for both issues, that's why i just opened one bug ticket.

This is what i observed:
- If i do an update to the content of an existing aws_ssm_document, it will not be updated on AWS side. The Terraform apply runs sucessfully without any errors. And no new Version of the document will be created.
- If i delete an existing aws_ssm_document within AWS, terraform doesn't recognize it. So if you run terraform apply, refresh or plan you will end with an InvalidDocument Error (code 400)

```hcl
X.Y.aws_ssm_document.patching: aws_ssm_document.patching: [ERROR] Error describing SSM document: InvalidDocument:
        status code: 400, request id: 3476859b-2a67-11e7-afcc-bfb008811cff
```

### Terraform Version
Terraform v0.9.2

### Affected Resource(s)
- aws_ssm_document

### Debug Output
With the Debug output enabled no further details can be found.

### Expected Behavior
- Updates done in terraform aws_ssm_document should be visible in AWS and a new version of the document should exist.
- Updates done in AWS should be noticed by terraform

### Actual Behavior
- Updates done in terraform are not visible within AWS
- Deleted documents in AWS should be noticed by terraform and recreated if configured.

### Steps to Reproduce
- Reproduce Update issue: 
-- Create a aws_ssm_document like i did it with the config below
-- terraform apply (here everything is fine, the new document will be created)
-- Change the tf config (e.g. change the content or description)
-- terraform apply (this run will suceed, but within AWS the changes are not visible, no new version is created)

- Reproduce Delete issue:
-- Delete the SSM Document in the AWS console
-- do a terraform plan run, then you will get the InvalidDocument Error.

### Terraform Configuration Files
```hcl
resource "aws_ssm_document" "patching" {
  name          = "patching"
  document_type = "Command"
  content = <<DOC
  {
    "schemaVersion": "2.0",
    "description": "Do the linux patching via yum",
    "parameters": {

    },
    "mainSteps": [
     {
        "action":"aws:runShellScript",
         "name":"runShellScript",
         "inputs": {
            "runCommand": ["yum -y update", "reboot"]
         }
      }
    ]
  }
DOC
}
```

### Workaround
For everyone who also runs in those issues, here is the workaround i did.
As the first creation of new aws_ssm_document's will work, you have to delete old aws_ssm_document's in the AWS Console and adjust the .tfstate file (delete the part of the aws_ssm_document). 

Hope you can fix the bug witin the next releases.
Kind regards,
Alex

**Comment by bclodius** [comment]
@awuetz I was able to reproduce on v0.9.2 but I am not able to reproduce on v0.9.3 +

Seems it was fixed on 0.9.3 looking at the CHANGELOG.

**Comment by thefringeninja** [comment]
Can you try v0.9.4? I believe we are having the same issue.

**Comment by stack72** [comment]
Hi @awuetz 

Please can you tell me if updating ssm documents is still an issue for you? I can't replicate it on master - I have replicated the `Invalid Document` issue though so am fixing this now

Thanks

Paul

**Comment by awuetz** [comment]
Hi *,

i did an update to v0.9.4 and the bug seems to be fixed there.
Many thanks for your replies.

Alex

**Comment by stack72** [comment]
Hi @awuetz 

Thanks for closing this off - I will fix the refresh issue as a followup PR anyway

Paul
