### ISSUE TITLE
google_project_services wants to repeatedly apply despite services being enabled in project

### ISSUE THREAD

**Issue by allandrick** [hashicorp/terraform#14509]
Hi there,

### Terraform Version
Terraform v0.9.4

### Affected Resource(s)
- google_project_services

### Terraform Configuration Files
```hcl
resource "google_project_services" "project-services" {
  project         = "${var.project_id}"
  services        = [
    "appengine.googleapis.com",
    "bigquery-json.googleapis.com",
    "cloudapis.googleapis.com",
    "cloudbuild.googleapis.com",
    "clouddebugger.googleapis.com",
    "cloudfunctions.googleapis.com",
    "cloudmonitoring.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "cloudtrace.googleapis.com",
    "compute-component.googleapis.com",
    "container.googleapis.com",
    "containerregistry.googleapis.com",
    "dataflow.googleapis.com",
    "dataproc.googleapis.com",
    "datastore.googleapis.com",
    "deploymentmanager.googleapis.com",
    "dns.googleapis.com",
    "iam.googleapis.com",
    "logging.googleapis.com",
    "monitoring.googleapis.com",
    "pubsub.googleapis.com",
    "replicapool.googleapis.com",
    "replicapoolupdater.googleapis.com",
    "resourceviews.googleapis.com",
    "runtimeconfig.googleapis.com",
    "spanner.googleapis.com",
    "speech.googleapis.com",
    "sqladmin.googleapis.com",
    "sql-component.googleapis.com",
    "storage-api.googleapis.com",
    "servicemanagement.googleapis.com",
    "storage-component.googleapis.com",
  ]
}
```

### Debug Output
This should be easily reproducible on a fresh GCP project created with terraform using 0.9.4 google_project resource syntax.  Contact me privately if a gist is required.

### Panic Output
None

### Expected Behavior
32 services should be enabled.  

### Actual Behavior
According to gcloud, 32 services are enabled.  According to Terraform Plan, 25 services are enabled and an apply is required.  Terraform apply does not change status of next terraform plan.

```
gcloud --project project-id service-management list | grep googleapis.com | wc -l
32
```

```
~ module.services.google_project_services.project-services
    services.#:          "25" => "32"
    services.1109577435: "cloudbuild.googleapis.com" => "cloudbuild.googleapis.com"
    services.133405307:  "" => "storage-component.googleapis.com"
    services.1560437671: "iam.googleapis.com" => "iam.googleapis.com"
    services.1610229196: "bigquery-json.googleapis.com" => "bigquery-json.googleapis.com"
    services.1633256984: "appengine.googleapis.com" => "appengine.googleapis.com"
    services.1712537408: "containerregistry.googleapis.com" => "containerregistry.googleapis.com"
    services.1793140363: "clouddebugger.googleapis.com" => "clouddebugger.googleapis.com"
    services.1904024597: "runtimeconfig.googleapis.com" => "runtimeconfig.googleapis.com"
    services.2117420113: "pubsub.googleapis.com" => "pubsub.googleapis.com"
    services.238136042:  "cloudapis.googleapis.com" => "cloudapis.googleapis.com"
    services.2471815660: "" => "servicemanagement.googleapis.com"
    services.2631575801: "" => "sqladmin.googleapis.com"
    services.2692275209: "dataproc.googleapis.com" => "dataproc.googleapis.com"
    services.2928564140: "dns.googleapis.com" => "dns.googleapis.com"
    services.2966512281: "deploymentmanager.googleapis.com" => "deploymentmanager.googleapis.com"
    services.2976624689: "cloudmonitoring.googleapis.com" => "cloudmonitoring.googleapis.com"
    services.3010261123: "replicapool.googleapis.com" => "replicapool.googleapis.com"
    services.3075019877: "replicapoolupdater.googleapis.com" => "replicapoolupdater.googleapis.com"
    services.3077910291: "resourceviews.googleapis.com" => "resourceviews.googleapis.com"
    services.323125032:  "cloudtrace.googleapis.com" => "cloudtrace.googleapis.com"
    services.3237295688: "monitoring.googleapis.com" => "monitoring.googleapis.com"
    services.3355193353: "logging.googleapis.com" => "logging.googleapis.com"
    services.3644083179: "cloudresourcemanager.googleapis.com" => "cloudresourcemanager.googleapis.com"
    services.3731214611: "compute-component.googleapis.com" => "compute-component.googleapis.com"
    services.3740470850: "container.googleapis.com" => "container.googleapis.com"
    services.3875785048: "" => "storage-api.googleapis.com"
    services.3899772697: "cloudfunctions.googleapis.com" => "cloudfunctions.googleapis.com"
    services.668598836:  "" => "spanner.googleapis.com"
    services.729731224:  "dataflow.googleapis.com" => "dataflow.googleapis.com"
    services.77316126:   "" => "sql-component.googleapis.com"
    services.932568001:  "datastore.googleapis.com" => "datastore.googleapis.com"
    services.9890082:    "" => "speech.googleapis.com"


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

### Important Factoids
Using 0.9.4 syntax for project creation from Terraform.

### References
None

**Comment by paddycarver** [comment]
Hi! Sorry you had issues. :( The good news is this was resolved by #13758, which was released in 0.9.5. So upgrading to 0.9.5 should solve the problem for you. Feel free to comment if it doesn't, and we'll reopen this issue.

**Comment by allandrick** [comment]
@paddycarver thank you!  I did search first, but didn't find the PR.  Next person to search will though 👍

**Comment by allandrick** [comment]
Hi @paddycarver this issue is still present in 0.9.11 (we haven't had a chance to try 10.x yet).

**Comment by oisin-unmortgage** [comment]
It looks like this may have regressed, unless I'm doing something wrong. I'm experiencing project with:

```
Terraform v0.11.7
+ provider.google v1.12.0
+ provider.random v1.2.0

```

With my terraform setup:

```
resource "google_project" "jenkins_prod_cloud" {
 name = "jenkins-prod-cloud"
 project_id = "jenkins-prod-cloud"
 billing_account = "${var.billing_account}"
 org_id = "${var.org_id}"
}

resource "google_project_services" "prod_jenkins_services" {
 project = "${google_project.jenkins_prod_cloud.project_id}"
 services = [
    "compute.googleapis.com",
    "containerregistry.googleapis.com",
  ]
}

```

I then do make plan and every time it keeps saying:

```

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ google_project_services.prod_jenkins_services
      services.#:          "0" => "2"
      services.1712537408: "" => "containerregistry.googleapis.com"
      services.2240314979: "" => "compute.googleapis.com"

  ~ google_project_services.prod_platform_services
      services.#:          "12" => "5"
      services.1568433289: "oslogin.googleapis.com" => "oslogin.googleapis.com"
      services.1610229196: "bigquery-json.googleapis.com" => ""
      services.1712537408: "containerregistry.googleapis.com" => "containerregistry.googleapis.com"
      services.2117420113: "pubsub.googleapis.com" => ""
      services.2240314979: "compute.googleapis.com" => "compute.googleapis.com"
      services.2928564140: "dns.googleapis.com" => "dns.googleapis.com"
      services.2966512281: "deploymentmanager.googleapis.com" => ""
      services.3010261123: "replicapool.googleapis.com" => ""
      services.3075019877: "replicapoolupdater.googleapis.com" => ""
      services.3077910291: "resourceviews.googleapis.com" => ""
      services.3740470850: "container.googleapis.com" => "container.googleapis.com"
      services.3875785048: "storage-api.googleapis.com" => ""


Plan: 0 to add, 2 to change, 0 to destroy.

```

Is there any fix or work around for this?

**Comment by paddycarver** [comment]
Where is the configuration for prod_platform_services? Also, why are you using two `google_project_services`? You can't apply two `google_project_services` to the same project, there must be only one per project.

**Comment by anners** [comment]
I am also having similar issues. The first apply the service gets enabled, subsequent runs it gets disabled and I get the following message:

Error refreshing state: 1 error(s) occurred:

* google_compute_shared_vpc_host_project.nonpci_shared: 1 error(s) occurred:

* google_compute_shared_vpc_host_project.nonpci_shared: google_compute_shared_vpc_host_project.nonpci_shared: Error reading Project data for project "nonpci-ef64cf79d1e324e6": googleapi: Error 403: Access Not Configured. Compute Engine API has not been used in project 998836409063 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=998836409063 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured

The only way to get past this is to enable in the console. 

resource "google_project" "nonpci_shared" {
 name            = "nonpci-x-${var.project_name}"
 project_id      = "nonpci-${random_id.nonpci_id.hex}"
 billing_account = "${var.billing_account}"
 org_id          = "${var.org_id}"
}

resource "google_project_services" "nonpci_shared" {
 project = "${google_project.nonpci_shared.project_id}"
 services = [
   "compute.googleapis.com"
 ]

**Comment by mildwonkey** [comment]
Hi @anners! Always nice to see ya 😁

You may want to open (or search for) an issue in the[ google provider repository](https://github.com/terraform-providers/terraform-provider-google) - terraform providers were [split out of the terraform codebase](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10) in 0.10.

Cheers!

**Comment by anners** [comment]
Hi @mildwonkey!!!! I guess I can bug people from my company about that repo. :) 

Thanks!
