### ISSUE TITLE
Terraform init fails with x509: certificate signed by unknown authority when using Zscaler

### ISSUE THREAD

**Issue by flyhard** [hashicorp/terraform#15713]
Hi there,
I am trying to run terraform 0.10.0, but` terraform init` fails with

```
$ terraform init

Initializing provider plugins...
- Downloading plugin for provider "aws"...

Error installing provider "aws": Get https://releases.hashicorp.com/terraform-provider-aws/: x509: certificate signed by unknown authority.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/darwin_amd64
```

My company is using ZScaler to mess with CA certificates, so I know that the reason is that the certificate used by HashiCorp is not the one I will see, but most applications have a switch to ignore it to let me run it anyways. 

Could we get a 'ignore certificate errors' switch, please?

**Comment by dsnellgrove** [comment]
Same issue here, also Mac OS. This behavior appears to be a regression in 0.10.0.

```
$ brew switch terraform 0.9.11
Cleaning /usr/local/Cellar/terraform/0.10.0
Cleaning /usr/local/Cellar/terraform/0.9.11
2 links created for /usr/local/Cellar/terraform/0.9.11

$ terraform init

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your environment. If you forget, other
commands will detect it and remind you to do so if necessary.

$ brew switch terraform 0.10.0
Cleaning /usr/local/Cellar/terraform/0.10.0
Cleaning /usr/local/Cellar/terraform/0.9.11
2 links created for /usr/local/Cellar/terraform/0.10.0

$ terraform init

Initializing provider plugins...
- Downloading plugin for provider "aws"...

Error installing provider "aws": Get https://releases.hashicorp.com/terraform-provider-aws/: x509: certificate signed by unknown authority.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/darwin_amd64

- Downloading plugin for provider "null"...

Error installing provider "null": Get https://releases.hashicorp.com/terraform-provider-null/: x509: certificate signed by unknown authority.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/darwin_amd64```

**Comment by dsnellgrove** [comment]
Oh, not quite new. This was probably an issue but wasn't visible until this change:

> Terraform providers are no longer distributed as part of the main Terraform distribution. Instead, they are installed automatically as part of running terraform init. It is therefore now mandatory to run terraform init before any other operations that use provider plugins, to ensure that the required plugins are installed and properly initialized.

**Comment by dsnellgrove** [comment]
@jbardin The ZScalar certificates are already trusted CAs on the system (otherwise not much would get done :) ), Terraform doesn't seem to be using them.

**Comment by jbardin** [comment]
@dsnellgrove, what is the system running terraform in your case?

**Comment by dsnellgrove** [comment]
Mac OS 10.12.6

**Comment by dsnellgrove** [comment]
It looks like Terraform no longer loads the correct parts of the Keychain due to changes in Go which prevents TLS validation when performing inspection (which is the ZScaler feature impacting us):
https://github.com/hashicorp/terraform/issues/12711
https://github.com/golang/go/issues/16532

**Comment by jbardin** [comment]
Yes, I'll take a look at the Go issue. The go1.9 code looks like it may be loading the correct keychains now even though that issue is still open, so hopefully that release will clear this up. 

Until then the quickest way forward is to fetch the providers manually.

**Comment by jbardin** [comment]
Hi,

The linked Go issue is fixed by 2 separate pieces, one of which has been recently merged and should fix our particular issue. That issue as a whole is marked as a go1.9 release blocker, so I'm fairly confident that the next Go release will close this for us.

**Comment by bitbrain** [comment]
I am also experiencing the exact same issue as explained by @dsnellgrove.

**Comment by pgr-mattgartman** [comment]
We are seeing this issue still as well and originally reported it in #12711.

Looking forward to a resolution.

**Comment by bitbrain** [comment]
@pgr-mattgartman Which terraform version are you using? I have upgraded to the latest version and for me it works now.

**Comment by pgr-mattgartman** [comment]
@bitbrain I was on an older version, I pulled down 0.10.6 and things seem to work fine on the mac now.  Looks like v0.10.2 switched the version over to go 1.9.

Thanks!

**Comment by jbardin** [comment]
Thanks for the confirmation @bitbrain.
While the upstream Go fix isn't complete, the terraform releases don't use cgo, and should now be getting the correct set of root certs.

**Comment by stancy007** [comment]
check proxy settings. I got this error but once I checked on proxy settings,I was able to work on TF

**Comment by omarabid** [comment]
I'm getting the same issue using the latest Terraform version on OSX

Error installing provider "null": Get https://releases.hashicorp.com/terraform-provider-null/: x509: certificate signed by unknown authority.

**Comment by dmceathron** [comment]
Also getting this issue using WSL(Ubuntu)

**Comment by bitbrain** [comment]
@dmceathron @omarabid which Terraform version are you using exactly? Also, what is the version of your local Go installation?

**Comment by omarabid** [comment]
@bitbrain Pretty sure was using the latest when I posted the comment. I don't have a Go installation as far as I'm aware.

**Comment by dmceathron** [comment]
@bitbrain 
Terraform v0.11.11
+ provider.aws v1.57.0
This issue has been resolved for me, I downloaded the zip of the provider I needed and put it in my terraform app dir.

**Comment by mmack** [comment]
Same problem here... 1.11.
