### ISSUE TITLE
Module output variables not interpolating when used in nested functions.

### ISSUE THREAD

**Issue by c4milo** [hashicorp/terraform#1997]
The interpolation that doesn't seem to be working is: 

```subnet_id = "${element(split(",", module.network.subnets), count.index)}"```

### network.tf
```tf
resource "aws_vpc" "main" {
	cidr_block = "${var.vpc_cidr}"
	tags {
		Name = "main"
	}
	enable_dns_support = true
	enable_dns_hostnames = true
}

resource "aws_internet_gateway" "managedbyq" {
	vpc_id = "${aws_vpc.main.id}"
}

resource "aws_route_table" "mycompany" {
	vpc_id = "${aws_vpc.main.id}"
	route {
		cidr_block = "0.0.0.0/0"
		gateway_id = "${aws_internet_gateway.mycompany.id}"
	}
}

resource "aws_main_route_table_association" "vpc-main-route-table" {
	vpc_id = "${aws_vpc.main.id}"
	route_table_id = "${aws_route_table.mycompany.id}"
}


resource "aws_subnet" "mycompany" {
	vpc_id = "${aws_vpc.main.id}"
	cidr_block = "${lookup(var.cidr_blocks, concat("zone", count.index))}"
	availability_zone = "${lookup(var.zones, concat("zone", count.index))}"
	map_public_ip_on_launch = true
	count = "${var.subnets_number}"
	tags {
		Name = "zone-${count.index+1}"
	}
}

resource "aws_route_table_association" "mycompany" {
    subnet_id = "${element(aws_subnet.mycompany.*.id, count.index)}"
    route_table_id = "${aws_route_table.mycompany.id}"
    count = "${var.subnets_number}"
}
```

### outputs.tf
```tf
output "subnets" {
	value = "${join(",", aws_subnet.mycompany.*.id)}"
}
```

### consul.tf
```tf
provider "aws" {
	access_key = "${var.access_key}"
	secret_key = "${var.secret_key}"
	region = "${var.region}"
}

module "network" {
	source = "../network"
	env = "${var.env}"
	parent_dns_zone = "${var.parent_dns_zone}"
	tld = "${var.tld}"
	vpc_cidr = "${var.vpc_cidr}"
	zones = "${var.zones}"
	cidr_blocks = "${var.cidr_blocks}"
	subnets_number = "${var.subnets_number}"
}

resource "aws_instance" "consul" {
	count = "${var.nodes}"
	ami = "${lookup(var.amis, var.region)}"
	instance_type = "${var.instance_type}"
	availability_zone = "${lookup(var.zones, concat("zone", count.index))}"
	vpc_security_group_ids = ["${module.network.common_security_group_id}"]

      // This is the line not working.
      subnet_id = "${element(split(",", module.network.subnets), count.index)}"
}
```

### Error

![](https://cldup.com/IUzqOTN2Qt.png)

### Dependency graph
![](https://cldup.com/EjRVD0pPoT.png)

**Comment by c4milo** [comment]
I omitted the rest of the configurations to avoid too much noise. Hopefully, the above should be illustrative enough.

**Comment by c4milo** [comment]
@radeksimko I did some more testing and found that `subnet_id = "${element(split(",", var.subnets), count.index)}"` works but `subnet_id = "${element(split(",", module.network.subnets), count.index)}"` does not. So, it seems like it could be an issue where module output variables are not being interpolated.

**Comment by radeksimko** [comment]
Interesting... I probably won't have enough time to debug it this week, but I remember @phinze was working on modules.

**Comment by c4milo** [comment]
@mitchellh I could attempt to fix this if you point me in the right direction. Thanks!

**Comment by mitchellh** [comment]
Hm, could you post the full debug log for this? I'm not quite sure how this is happening yet. Or, if you could get a more minimal repro case, that would help as well.

**Comment by juls** [comment]
I guess I'm facing the same problem here and put up a minimal [example](https://github.com/juls/terraform-module-output). To reproduce it, please
* set your DOCKER_* environment variables for the [docker provider](https://www.terraform.io/docs/providers/docker/index.html#host)
* Uncomment one one of [these three lines](https://github.com/juls/terraform-module-output/blob/master/main.tf#L19-L26)
* run the example with `terraform get && terraform apply`

**Comment by mitchellh** [comment]
@juls Just letting you know the last line has been fixed in a PR (but isn't merged yet)

**Comment by mitchellh** [comment]
I believe with the latest round of PRs, this should be fixed. Can you verify... in a few days? (Once they all marge in). Let me know if its not. I made a config like yours (but not exactly... hard to) and it worked. If it isn't fixed, if we can get a more direct repro case (like a repro repo), that'd be super great!

**Comment by juls** [comment]
@mitchellh `terraform apply` now works as expected, but `terraform destroy` still throws the same error on the latest dev build (_Terraform v0.6.0-dev (e5a9cee5bb25cc05211a9055bd0fb14c8ff5bfdf)_).

I've updated my [example](https://github.com/juls/terraform-module-output), you can reproduce the problem with `terraform get && terraform apply && terraform destroy -force`

**Comment by rgabo** [comment]
@mitchellh thanks for getting this merged back. I'm wondering how often dev builds make it to Atlas. Atlas is currently at v0.6.0-dev (cb36bac), a June 3 commit. Being a non-prod environment, I can easily reset state and start from scratch, but I was wondering what the *release policy* for dev builds in Atlas were. Thanks!
