### ISSUE TITLE
Templates are not picking up new variables

### ISSUE THREAD

**Issue by jwaldrip** [hashicorp/terraform#2013]
New variables are not being picked up by templates. They now come through as `variable undefined`

**Comment by jwaldrip** [comment]
Just confirmed. Reverting back to 0.5.0 makes this work.

**Comment by bakins** [comment]
I had same issue and if I delete `terraform.tfstate.backup` and `terraform.tfstate`, it works

**Comment by adelamarre** [comment]
You could work around if you remove the template_file object in the state .json file.

**Comment by josephholsten** [comment]
@phinze should be closed by #2386

**Comment by phinze** [comment]
Yep - fixed in master. Fix will come out with 0.6

**Comment by rvangundy** [comment]
I believe I'm still encountering this error when running via Atlas. I can see that the variables are set on the environment, but get the variable undefined error.

**Comment by rvangundy** [comment]
Still encountering this issue when running through Atlas.

**Comment by phinze** [comment]
@rvangundy thanks for the heads up - I believe the Terraform version used by Atlas just needs to be updated. Will follow up here once I've looked into it.
