### ISSUE TITLE
Terraform v0.12-rc1 panic on invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by ziporah** [hashicorp/terraform#21383]
Terraform crashes on initialisation with segmentation violation

### Terraform Version
```
10:16 $ terraform-v0.12-rc1 -v
Terraform v0.12.0-rc1
```

### Terraform Configuration Files
```hcl
module "gce-container" {
  source  = "github.com/terraform-google-modules/terraform-google-container-vm"
  version = "0.3.0"

  container = { 
    image = "jenkins/jenkins:lts"
    name  = "jenkins"
    env = [ 
      {   
        name  = "JENKINS"
        value = "Hello World!"
      },  
    ]   
  }
  restart_policy = "Always"
}

```

### Debug Output

https://gist.github.com/ziporah/c1d5be13f2e31f49879dc4d5370377e9

### Crash Output

crash.log file : 
https://gist.github.com/ziporah/3f12703dbfb9fce04b0e5db81eabf301

### Expected Behavior

The module should initialise and work

### Actual Behavior
Terraform segfaults and stops

### Steps to Reproduce
Any terraform init / plan / apply / refresh action will crash with segfault

### References
Opened issue with the module provider as well:

https://github.com/terraform-google-modules/terraform-google-container-vm/issues/25

**Comment by apparentlymart** [comment]
Hi @ziporah! Sorry for this crash, and thanks for reporting it.

I think what you've hit here is the same bug that was subsequently fixed in #21329: the `version` argument is not acceptable here because versioning is only for modules being installed from a Terraform Registry, while this one is coming from a GitHub repository directly.

The expected behavior here would be an error message saying that `version` is not accepted, which is the behavior that #21329 restored.

To select a specific branch or tag from a Git repository requires [a `ref` argument on the address](https://www.terraform.io/docs/modules/sources.html#selecting-a-revision), because that is handled by the Git "getter" rather than by Terraform itself.

**Comment by ziporah** [comment]
I switched to using the terraform provided google provider and this issue is solved now. There is still a problem with the provider code itself, but I managed to solve this. I will put in a PR with the provider for this. (ref)[https://github.com/terraform-google-modules/terraform-google-container-vm/pull/26]

**Comment by apparentlymart** [comment]
Thanks for confirming that, @ziporah! In that case, I'm going to close this issue.
