### ISSUE TITLE
Unexpected cycle error on destroy

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform#21410]
### Terraform Version

```
Terraform v0.12.0
* provider.aws: version = "~> 2.11"

```

### Terraform Configuration Files

```hcl
module "vpc" {
  source     = "./modules/vpc"
  vpc_name   = "vpc-apn01-stage"
  vpc_cidr   = "172.31.0.0/16"
  vpc_env    = "stage"
  aws_region = "ap-northeast-1"
}

module "subnets_ap-northeast-1a" {
  source      = "./modules/subnets"
  vpc         = module.vpc
  subnet_az   = "ap-northeast-1a"

  public = {
      subnet_name = "sample1a_public"
      subnet_cidr = "172.31.1.0/24"
  }

  private = [
      {
        subnet_name = "sample1a_private1"
        subnet_cidr = "172.31.10.0/24"
      },
      {
        subnet_name = "sample1a_private2"
        subnet_cidr = "172.31.11.0/24"
      }
  ]
}
```
vpc module:

```hcl
data "aws_caller_identity" "current" {
}

resource "aws_vpc" "this" {
  cidr_block = "${var.vpc_cidr}"
   
  tags = {
    Name        = "${var.vpc_name}"
    Environment = "${var.vpc_env}"
  }
}

resource "aws_internet_gateway" "igw" {
  vpc_id = "${aws_vpc.this.id}"

  tags = {
    Name = "igw-${var.vpc_name}"
  }
}

resource "aws_default_security_group" "default" {
  vpc_id = "${aws_vpc.this.id}"
}

resource "aws_key_pair" "deploy" {
  key_name   = "deploy-key"
  public_key = "ssh-rsa xxxx"
}

data "aws_region" "current" {
}

output "vpc_name" {
  value = "${var.vpc_name}"
}

output "vpc_cidr" {
  value = "${var.vpc_cidr}"
}

output "vpc_id" {
  value = "${aws_vpc.this.id}"
}

output "vpc_env" {
  value = "${var.vpc_env}"
}

output "aws_region" {
  value = "${data.aws_region.current.name}"
}

output "igw_id" {
  value = "${aws_internet_gateway.igw.id}"
}

output "default_security_group_id" {
  value = "${aws_default_security_group.default.id}"
}

output "account_id" {
  value = "${data.aws_caller_identity.current.account_id}"
}

output "deploy_key" {
  value = "${aws_key_pair.deploy.key_name}"
}
```

subnet module:
```hcl
resource "aws_subnet" "public" {
  vpc_id            = "${var.vpc["vpc_id"]}"
  cidr_block        = "${var.public.subnet_cidr}"
  availability_zone = "${var.subnet_az}"

  tags = {
    Name = "${var.public.subnet_name}"
  }
}

resource "aws_route_table" "public_route_table" {
  vpc_id = "${var.vpc["vpc_id"]}"

  tags = {
    Name = "public-${var.subnet_az}"
  }
}

resource "aws_route_table" "private_route_table" {
  vpc_id = "${var.vpc["vpc_id"]}"

  tags = {
    Name = "private-${var.subnet_az}"
  }
}

resource "aws_route" "igw_route" {
  route_table_id         = "${aws_route_table.public_route_table.id}"
  destination_cidr_block = "0.0.0.0/0"
  gateway_id             = "${var.vpc["igw_id"]}"
}

resource "aws_route_table_association" "rt_assn" {
  subnet_id      = "${aws_subnet.public.id}"
  route_table_id = "${aws_route_table.public_route_table.id}"
}

resource "aws_eip" "nat" {
  vpc      = true
}

resource "aws_nat_gateway" "natgw" {
  allocation_id = "${aws_eip.nat.id}"
  subnet_id     = "${aws_subnet.public.id}"

  tags = {
    Name = "natgw-${var.subnet_az}"
  }
}

resource "aws_route" "nat_route" {
  route_table_id         = "${aws_route_table.private_route_table.id}"
  destination_cidr_block = "0.0.0.0/0"
  nat_gateway_id             = "${aws_nat_gateway.natgw.id}"
}

resource "aws_subnet" "private" {
  count             = length(var.private)
  vpc_id            = var.vpc["vpc_id"]
  cidr_block        = lookup(var.private[count.index], "subnet_cidr")
  availability_zone = var.subnet_az

  tags = {
    Name = lookup(var.private[count.index], "subnet_name")
  }
}

resource "aws_route_table_association" "rt_assn_private" {
  count          = length(var.private)
  subnet_id      = aws_subnet.private[count.index].id
  route_table_id = aws_route_table.private_route_table.id
}
```

### Expected Behavior
terraform destroy should have removed resources created by `vpc` and `subnet` modules.

### Actual Behavior
Error: Cycle: module.vpc.aws_key_pair.deploy (destroy), module.vpc.data.aws_caller_identity.current (destroy), module.vpc.aws_internet_gateway.igw (destroy), module.vpc.aws_default_security_group.default (destroy), module.vpc.aws_vpc.this (destroy), module.subnets_ap-northeast-1a.aws_route_table.public_route_table (destroy), module.subnets_ap-northeast-1a.aws_subnet.private[0] (destroy), module.subnets_ap-northeast-1a.aws_subnet.private[1] (destroy), module.subnets_ap-northeast-1a.aws_route.igw_route (destroy), module.subnets_ap-northeast-1a.aws_nat_gateway.natgw (destroy), module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn (destroy), module.subnets_ap-northeast-1a.aws_subnet.public (destroy), module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn_private[1] (destroy), module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn_private[0] (destroy), module.subnets_ap-northeast-1a.aws_route_table.private_route_table (destroy), module.vpc.data.aws_region.current (destroy), module.subnets_ap-northeast-1a.var.vpc, output.subnets, module.subnets_ap-northeast-1a.aws_route.nat_route (destroy)

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform destroy`

### Additional Context

Terraform is running inside docker via gitlab CI runner. This behavior is only reproducible by running `terraform destroy`, removing the subnet module from the configuration and then running `terraform apply` results in a clean destroy by terraform. It seems that terraform is seeing some dependency between the `vpc` and `subnet` module that may not actually exist. The `subnet` module uses `module.vpc` as in input variable, however the `vpc` module does not have a dependency on any resource created by the `subnet` module. 

Graphing the dependency via "terraform graph -verbose -draw-cycles" did not yield any insight as to where a cycle may be either: [link](https://dreampuf.github.io/GraphvizOnline/#digraph%20%7B%0A%09compound%20%3D%20%22true%22%0A%09newrank%20%3D%20%22true%22%0A%09subgraph%20%22root%22%20%7B%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_eip.nat%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.aws_eip.nat%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_nat_gateway.natgw%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.aws_nat_gateway.natgw%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route.igw_route%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.aws_route.igw_route%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route.nat_route%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.aws_route.nat_route%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table.private_route_table%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.aws_route_table.private_route_table%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table.public_route_table%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.aws_route_table.public_route_table%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn_private%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn_private%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_subnet.private%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.aws_subnet.private%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_subnet.public%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.aws_subnet.public%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.output.private%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.output.private%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.output.public%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.output.public%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.private%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.var.private%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.public%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.var.public%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.subnet_az%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.var.subnet_az%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%20%5Blabel%20%3D%20%22module.subnets_ap-northeast-1a.var.vpc%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.aws_default_security_group.default%22%20%5Blabel%20%3D%20%22module.vpc.aws_default_security_group.default%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.aws_internet_gateway.igw%22%20%5Blabel%20%3D%20%22module.vpc.aws_internet_gateway.igw%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.aws_key_pair.deploy%22%20%5Blabel%20%3D%20%22module.vpc.aws_key_pair.deploy%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.aws_vpc.this%22%20%5Blabel%20%3D%20%22module.vpc.aws_vpc.this%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.data.aws_caller_identity.current%22%20%5Blabel%20%3D%20%22module.vpc.data.aws_caller_identity.current%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.data.aws_region.current%22%20%5Blabel%20%3D%20%22module.vpc.data.aws_region.current%22%2C%20shape%20%3D%20%22box%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.output.account_id%22%20%5Blabel%20%3D%20%22module.vpc.output.account_id%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.output.aws_region%22%20%5Blabel%20%3D%20%22module.vpc.output.aws_region%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.output.default_security_group_id%22%20%5Blabel%20%3D%20%22module.vpc.output.default_security_group_id%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.output.deploy_key%22%20%5Blabel%20%3D%20%22module.vpc.output.deploy_key%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.output.igw_id%22%20%5Blabel%20%3D%20%22module.vpc.output.igw_id%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.output.vpc_cidr%22%20%5Blabel%20%3D%20%22module.vpc.output.vpc_cidr%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.output.vpc_env%22%20%5Blabel%20%3D%20%22module.vpc.output.vpc_env%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.output.vpc_id%22%20%5Blabel%20%3D%20%22module.vpc.output.vpc_id%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.output.vpc_name%22%20%5Blabel%20%3D%20%22module.vpc.output.vpc_name%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.var.aws_region%22%20%5Blabel%20%3D%20%22module.vpc.var.aws_region%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.var.vpc_cidr%22%20%5Blabel%20%3D%20%22module.vpc.var.vpc_cidr%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.var.vpc_env%22%20%5Blabel%20%3D%20%22module.vpc.var.vpc_env%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20module.vpc.var.vpc_name%22%20%5Blabel%20%3D%20%22module.vpc.var.vpc_name%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20output.subnets%22%20%5Blabel%20%3D%20%22output.subnets%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20output.vpc%22%20%5Blabel%20%3D%20%22output.vpc%22%2C%20shape%20%3D%20%22note%22%5D%0A%09%09%22%5Broot%5D%20provider.aws%22%20%5Blabel%20%3D%20%22provider.aws%22%2C%20shape%20%3D%20%22diamond%22%5D%0A%09%09%22%5Broot%5D%20provider.aws%20(close)%22%20%5Blabel%20%3D%20%22provider.aws%20(close)%22%2C%20shape%20%3D%20%22diamond%22%5D%0A%09%09%22%5Broot%5D%20meta.count-boundary%20(EachMode%20fixup)%22%20-%3E%20%22%5Broot%5D%20output.subnets%22%0A%09%09%22%5Broot%5D%20meta.count-boundary%20(EachMode%20fixup)%22%20-%3E%20%22%5Broot%5D%20output.vpc%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_eip.nat%22%20-%3E%20%22%5Broot%5D%20provider.aws%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_nat_gateway.natgw%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_eip.nat%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_nat_gateway.natgw%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_subnet.public%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route.igw_route%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table.public_route_table%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route.nat_route%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_nat_gateway.natgw%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route.nat_route%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table.private_route_table%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table.private_route_table%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.subnet_az%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table.private_route_table%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table.public_route_table%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.subnet_az%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table.public_route_table%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table.public_route_table%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_subnet.public%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn_private%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table.private_route_table%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn_private%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_subnet.private%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_subnet.private%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.private%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_subnet.private%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.subnet_az%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_subnet.private%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_subnet.public%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.public%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_subnet.public%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.subnet_az%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_subnet.public%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.output.private%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_subnet.private%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.output.public%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_subnet.public%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.account_id%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.aws_region%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.default_security_group_id%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.deploy_key%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.igw_id%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.vpc_cidr%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.vpc_env%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.vpc_id%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.vpc_name%22%0A%09%09%22%5Broot%5D%20module.subnets_ap-northeast-1a.var.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.var.aws_region%22%0A%09%09%22%5Broot%5D%20module.vpc.aws_default_security_group.default%22%20-%3E%20%22%5Broot%5D%20module.vpc.aws_vpc.this%22%0A%09%09%22%5Broot%5D%20module.vpc.aws_internet_gateway.igw%22%20-%3E%20%22%5Broot%5D%20module.vpc.aws_vpc.this%22%0A%09%09%22%5Broot%5D%20module.vpc.aws_key_pair.deploy%22%20-%3E%20%22%5Broot%5D%20provider.aws%22%0A%09%09%22%5Broot%5D%20module.vpc.aws_vpc.this%22%20-%3E%20%22%5Broot%5D%20module.vpc.var.vpc_cidr%22%0A%09%09%22%5Broot%5D%20module.vpc.aws_vpc.this%22%20-%3E%20%22%5Broot%5D%20module.vpc.var.vpc_env%22%0A%09%09%22%5Broot%5D%20module.vpc.aws_vpc.this%22%20-%3E%20%22%5Broot%5D%20module.vpc.var.vpc_name%22%0A%09%09%22%5Broot%5D%20module.vpc.aws_vpc.this%22%20-%3E%20%22%5Broot%5D%20provider.aws%22%0A%09%09%22%5Broot%5D%20module.vpc.data.aws_caller_identity.current%22%20-%3E%20%22%5Broot%5D%20provider.aws%22%0A%09%09%22%5Broot%5D%20module.vpc.data.aws_region.current%22%20-%3E%20%22%5Broot%5D%20provider.aws%22%0A%09%09%22%5Broot%5D%20module.vpc.output.account_id%22%20-%3E%20%22%5Broot%5D%20module.vpc.data.aws_caller_identity.current%22%0A%09%09%22%5Broot%5D%20module.vpc.output.aws_region%22%20-%3E%20%22%5Broot%5D%20module.vpc.data.aws_region.current%22%0A%09%09%22%5Broot%5D%20module.vpc.output.default_security_group_id%22%20-%3E%20%22%5Broot%5D%20module.vpc.aws_default_security_group.default%22%0A%09%09%22%5Broot%5D%20module.vpc.output.deploy_key%22%20-%3E%20%22%5Broot%5D%20module.vpc.aws_key_pair.deploy%22%0A%09%09%22%5Broot%5D%20module.vpc.output.igw_id%22%20-%3E%20%22%5Broot%5D%20module.vpc.aws_internet_gateway.igw%22%0A%09%09%22%5Broot%5D%20module.vpc.output.vpc_cidr%22%20-%3E%20%22%5Broot%5D%20module.vpc.var.vpc_cidr%22%0A%09%09%22%5Broot%5D%20module.vpc.output.vpc_env%22%20-%3E%20%22%5Broot%5D%20module.vpc.var.vpc_env%22%0A%09%09%22%5Broot%5D%20module.vpc.output.vpc_id%22%20-%3E%20%22%5Broot%5D%20module.vpc.aws_vpc.this%22%0A%09%09%22%5Broot%5D%20module.vpc.output.vpc_name%22%20-%3E%20%22%5Broot%5D%20module.vpc.var.vpc_name%22%0A%09%09%22%5Broot%5D%20output.subnets%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route.igw_route%22%0A%09%09%22%5Broot%5D%20output.subnets%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route.nat_route%22%0A%09%09%22%5Broot%5D%20output.subnets%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn%22%0A%09%09%22%5Broot%5D%20output.subnets%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn_private%22%0A%09%09%22%5Broot%5D%20output.subnets%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.output.private%22%0A%09%09%22%5Broot%5D%20output.subnets%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.output.public%22%0A%09%09%22%5Broot%5D%20output.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.account_id%22%0A%09%09%22%5Broot%5D%20output.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.aws_region%22%0A%09%09%22%5Broot%5D%20output.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.default_security_group_id%22%0A%09%09%22%5Broot%5D%20output.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.deploy_key%22%0A%09%09%22%5Broot%5D%20output.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.igw_id%22%0A%09%09%22%5Broot%5D%20output.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.vpc_cidr%22%0A%09%09%22%5Broot%5D%20output.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.vpc_env%22%0A%09%09%22%5Broot%5D%20output.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.vpc_id%22%0A%09%09%22%5Broot%5D%20output.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.output.vpc_name%22%0A%09%09%22%5Broot%5D%20output.vpc%22%20-%3E%20%22%5Broot%5D%20module.vpc.var.aws_region%22%0A%09%09%22%5Broot%5D%20provider.aws%20(close)%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route.igw_route%22%0A%09%09%22%5Broot%5D%20provider.aws%20(close)%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route.nat_route%22%0A%09%09%22%5Broot%5D%20provider.aws%20(close)%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn%22%0A%09%09%22%5Broot%5D%20provider.aws%20(close)%22%20-%3E%20%22%5Broot%5D%20module.subnets_ap-northeast-1a.aws_route_table_association.rt_assn_private%22%0A%09%09%22%5Broot%5D%20root%22%20-%3E%20%22%5Broot%5D%20meta.count-boundary%20(EachMode%20fixup)%22%0A%09%09%22%5Broot%5D%20root%22%20-%3E%20%22%5Broot%5D%20provider.aws%20(close)%22%0A%09%7D%0A%7D%0A)

**Comment by langecode** [comment]
We are seeing something similar and a lot of digging in the debug output may have revealed the problem. Basically it seems that the module output gets a dependency upon the destruction of the resources in the module which causes the cycle.

Say I have "module A" with "resource A" producing "output A". In the root I have "resource B" which depends on "module A.output A".

Terraform figures out that "resource B" must be destroyed _before_ "resource A" - so
`"resource A (destroy)" -> "resource B (destroy)"`
so far so good. Also
`"resource B (destroy)" -> "module A.output A"`
which is also fine. Now comes the cycle because it seems that
`"module A.output A" -> "resource A (prepare state)", "resource A (destroy)"`
which then causes the cycle.

In my cases it is actually a provider in the root module which is dependent upon the output from a submodule so the cycle has a few extra steps - but in essense the cycle is caused by the module output becoming dependent on the destruction of the resource in the module.

Below is the part the output from our actually project. The module output gets dependent on "destroy" and ends up causing a cycle.

```
module.kubernetes.output.kube_config
  module.kubernetes.azurerm_kubernetes_cluster.k8s (destroy)
  module.kubernetes.azurerm_kubernetes_cluster.k8s (prepare state)
provider.kubernetes
  module.kubernetes.output.kube_config
kubernetes_role_binding.seb-helm-binding (destroy)
  kubernetes_role_binding.seb-helm-binding (prepare state)
  provider.kubernetes
kubernetes_role_binding.seb-helm-binding (prepare state)
  provider.kubernetes
module.kubernetes.azurerm_kubernetes_cluster.k8s (destroy)
  kubernetes_role_binding.seb-helm-binding (destroy)
  ...
```

**Comment by neekz0r** [comment]
I think I'm seeing an aspect of this issue. 

Interestingly, I can run a destroy fine. Where I encounter a cycle error is if I increase a resource count, and then decrease it.

EG: create an instance using a module (passing a count to the module), attach IPs using another module based upon the output instance IDs from the former.

After decrease the count to the initial module, the cycle error pops up.

**Comment by jpreese** [comment]
@langecode it seems like we are experiencing this as well. Did you end up finding a work around? We're using the `kube_admin_config` from the `azurerm_kubernetes_cluster` in the provider block for Kubernetes.

**Comment by langecode** [comment]
Nope, I haven't had time to further dig into it.. I currently have a provider definition inside the module too, I am wondering whether it changes the cycle to only define the providers at the root level. But haven't had the time to test this out.

**Comment by jpreese** [comment]
Yeah, it does seem a little silly that we need to destroy resources on a cluster that we are destroying.

**Comment by arbourd** [comment]
I see the issue when attempting to change the SSD count of `google_container_cluster` which would force a recreate (destroy -> create).

No module use, no outputs. No cycles drawn on the graph.

**Comment by checkmypi** [comment]
I have the same problem using only aws provider data sources

Here's a simple setup to reproduce

**a/main.tf**
```terraform
data "aws_caller_identity" "current_aws_account" {
}

output "account_dns_zone" {
  value = "my.existing.dns.zone.com"
}
```
**b/main.tf**
```terraform
variable "common" {
}

data "aws_route53_zone" "account_zone" {
  name = "${var.common.account_dns_zone}."
}

output "account_dns_zone_id" {
  value = data.aws_route53_zone.account_zone.id
}
```
**main.tf**
```terraform
provider "aws" {
  region = "us-east-1"
}

module "mod_a" {
  source = "./a"

  providers = {
    aws = aws
  }
}

module "mod_b" {
  source = "./b"
  common = module.mod_a

  providers = {
    aws = aws
  }
}

output "mod_b" {
  value = module.mod_b
}
```

And a shell command used to destroy

```
terraform destroy -auto-approve -lock=true -lock-timeout=0s -input=false  -parallelism=10 -refresh=true
```

**Comment by aliusmiles** [comment]
FYI: similar issue was fixed in latest terraform versions, might be this one is already fixed as well: https://github.com/hashicorp/terraform/issues/21662

**Comment by checkmypi** [comment]
@aliusmiles  unfortunately that's not the case I've tested it with 0.12.18 and I still get the same error

**Comment by simonklb** [comment]
I'm experiencing the same issue. I first saw this while using remote execution in Terraform Cloud. However, I discovered that `terraform destroy` locally works fine while `terraform plan -destroy -out=destroy.tfplan` followed by `terraform apply destroy.tfplan` does not.

Another thing that might be of interest is that graphing the plan isn't working either:
```
terraform graph -verbose -draw-cycles ./destroy.tfplan                                                

Error: Failed to read module directory

Module directory  does not exist or cannot be read.
```

The issue seems to be that the plan is generating a cycle when configuring a provider with the output from a module.

Version 0.12.18 both on remote and local.

**Comment by DevOpsFu** [comment]
> 
> 
> However, I discovered that `terraform destroy` locally works fine while `terraform plan -destroy -out=destroy.tfplan` followed by `terraform apply destroy.tfplan` does not.
> 
> Version 0.12.18 both on remote and local.

I have seen exactly the same behaviour, and I never thought to try a direct `destroy` until I saw your message @simonklb .

I'm using 0.12.18 also, creating an AKS cluster in Azure and using the outputs from that to initialise the Kubernetes and Helm providers in the root module.  Planning a destroy to a file and then applying that gives the Cycle error. Doing a direct `terraform destroy` does not.

**Comment by eskp** [comment]
This is still an issue on Terraform cloud as that runs the two separate commands opposed to the single destroy.

**Comment by dkirrane** [comment]
Any workaround for Terraform Cloud? It will always do:
`terraform plan -destroy -out=destroy.tfplan` followed by `terraform apply destroy.tfplan`

**Comment by saranicole** [comment]
@dkirrane  the workaround I used for Terraform Cloud was to switch to Local instead of Remote execution and run `terraform destroy` directly from my laptop.  Not the best but it allows me to keep the state file up to date and better than deleting everything by hand.

**Comment by abdennour** [comment]
@saranicole What does it mean 
> switch to Local instead of Remote execution

**Comment by okgolove** [comment]
@abdennour as far as I understand that's about Terraform Cloud settings:
![image](https://user-images.githubusercontent.com/36846182/92327745-9840c980-f064-11ea-807b-2747366e3541.png)

**Comment by chrizkim** [comment]
Had a similar issue as @langecode and @jpreese outputting the `kube_config` from a module creating an AKS cluster and using it in the `kubernetes` provider block. I was getting the cycle on `destroy` through Terraform 0.13.2, but after updating to 0.13.3, the problem seems to have gone away for me.

**Comment by jbardin** [comment]
Hello All,

I have verified that this particular example works in current releases, and the known instances of this type of cycle have been resolved in general.

If anyone has similar error with 0.15 or later, please file a new issue with an example to reproduce the error.

Thanks!
