### ISSUE TITLE
Cannot Back Out of Terraform Upgrade After Apply

### ISSUE THREAD

**Issue by enummela** [hashicorp/terraform#23290]
I upgraded my terraform CLI from 0.12.9 to 0.12.13 while attempting to fix a problem unrelated to this bug report. In the process of dubugging this problem, I ran `terraform apply` unsuspecting that it would seemingly (for all intents and purposes) break my state in 0.12.9 forever.

It turns out my problem was not solved by upgrading my CLI to 0.12.13 so I downgraded it back to 0.12.9. However, now in my Terraform project and all projects that pull in its state remotely I am experiencing this error on `plan` and `apply`.

```
Error: state snapshot was created by Terraform v0.12.13, which is newer than current v0.12.9; upgrade to Terraform v0.12.13 or greater to work with this state
```

### Expected Behavior

After upgrading to 0.12.13, on running `terraform apply` a prominent message is displayed warning me that continuing will upgrade my state and that it will be unusable in older versions of Terraform. Ideally, I would also have to provide some kind of flag or argument to bypass this warning so that I don't accidentally lock my state into this newer release.

Alternatively, some kind of mechanism will exist allowing me to revert my state snapshot to a format that's compatible with the older release (0.12.9).

### Actual Behavior

My Terraform project is now dependent on 0.12.13 so now all of my team members and I have to upgrade our CLIs and upgrade the CLI in our CI pipeline Docker image.

**Comment by hposca** [comment]
I'm also getting a `Error: state snapshot was created by Terraform v0.12.13, which is newer than current v0.12.8; upgrade to Terraform v0.12.13 or greater to work with this state` message.

And my scenario is even stranger... My terraform executable and state file are still on version `0.12.8`:

```
$ terraform --version
Terraform v0.12.8

$ terraform state pull | grep terraform_version
  "terraform_version": "0.12.8",
```

It also uses `S3` as backend, and I believe that nobody in the company did a `terraform apply` (`0.12.13`) as `terraform_version` is still `0.12.8` on the state file.

We are using `0.12.13` on other completely different resources, with their respective state files. (I don't see how, but) Is there a chance of "cross-contamination" (via the DynamoDB table or something else)?

P.S.: We are using [tfenv](https://github.com/tfutils/tfenv) to run different versions of terraform depending on what we are building.

**Comment by dogzzdogzz** [comment]
same issue here, we have teams in terraform collaboration, i don't want to be forced to upgrade my terraform version frequently just because someone use a newer version but actually there is no breaking change in tfstate between two versions.

**Comment by hposca** [comment]
This happened again today.

`Error: state snapshot was created by Terraform v0.12.18, which is newer than current v0.12.17; upgrade to Terraform v0.12.18 or greater to work with this state`

```bash
$ terraform --version
Terraform v0.12.17

$ terraform state pull | grep terraform_version
  "terraform_version": "0.12.17",
```

**Comment by hoangnguyenba** [comment]
This happens again today :(
`Error refreshing state: state snapshot was created by Terraform v0.12.18, which is newer than current v0.12.16; upgrade to Terraform v0.12.18 or greater to work with this state`

`terraform --version
2019/12/31 11:58:12 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2019/12/31 11:58:12 Loading CLI configuration from /Users/heakthone3/.terraformrc
Terraform v0.12.18
+ provider.acme v1.5.0
+ provider.alicloud v1.67.0
+ provider.digitalocean v1.12.0
+ provider.helm v0.10.4
+ provider.kubernetes v1.10.0
+ provider.tls v2.1.1`

**Comment by hoangnguyenba** [comment]
In my case, I need to go remote state and update the version to 0.12.18

**Comment by voldemortensen** [comment]
This happened to me today. I imported a resource from Kubernetes, which updated the state. State is kept in Terraform Cloud. `terraform plan` won't complete because of this error. It seems that Terraform Cloud hasn't updated the system that runs the plans.

**Comment by voldemortensen** [comment]
In case anyone else needs it, I stumbled upon this in Terraform Cloud in `Settings > General`.

```The version of Terraform to use for this workspace. Upon creating this workspace, the latest version was selected and will be used until it is changed manually. It will not upgrade automatically.```

Changing this resolved my issue. Very inconvenient, but that's the solution.

**Comment by nikhils5501** [comment]
I had this same issue. 
If you see this error, its not just the version of the terraform state that you are accessing/running plan against. Terraform cross-references a lot of terraform states internally. So just go inside the remote state bucket and try to find that one specific remote state with `different tf version`.

In my case, I was running a tf plan for resource 'X' that clearly had the remote state version `0.12.8`. But resource 'X' was global and it was referencing another totally different resource Y's state with `0.12.14` which is why, I was getting the error. Just open the bad remote state in a text editor and change the `"terraform_version"` value to the default version that you want. This will fix it 👍

**Comment by msotoperdomo** [comment]
Same issue here. Getting a plan error for when the remote state version is greater than the state that uses it.
```
error loading the remote state: state snapshot was created by Terraform
v0.12.13, which is newer than current v0.12.12; upgrade to Terraform v0.12.13
or greater to work with this state
```
I use the same remote state in a terraform version `0.11.14` and this validation is not present. Plan works fine.

**Comment by mike-dazn** [comment]
Still happening on `0.12.23/0.12.24`

```
Error: state snapshot was created by Terraform v0.12.24, which is newer than current v0.12.23; upgrade to Terraform v0.12.24 or greater to work with this state
```

With this issue, it makes remote state an absolute nightmare to manage.

**Comment by garrypas** [comment]
This bug needs to be fixed, causes huge amounts of hassle. Upgrading isn't always an option, and trying to aggressively force people down this path is wrong. People use the wrong version and the state is basically screwed, I've never seen an effective solution to this other than spending days digging into buckets to remove residual crap that terraform refuses to destroy by hand and start afresh.

**Comment by gurrpi** [comment]
Still happening on `0.12.21/0.12.16`
```
Error refreshing state: state snapshot was created by Terraform v0.12.21, which is newer than current v0.12.16; upgrade to Terraform v0.12.21 or greater to work with this state
```

**Comment by etwillbefine** [comment]
I have the same issue with Terraform 0.12.24. Error: `state snapshot was created by Terraform v0.12.24, which is newer than current v0.12.19`.

This happens to me once an autoplan was triggered and failed and I run `atlantis plan` again. The default tf version and project config are both set to `0.12.24` but the binary installed on the docker image used version 0.12.19. So somehow running `atlantis plan` after a plan was already created causes the "local binary" (shipped with the docker image) to be used.

**Comment by Jangmin-Lee** [comment]
I have the same issue with 0.12.20 -> 0.12.24
`Error refreshing state: state snapshot was created by Terraform v0.12.24, which is newer than current v0.12.20; upgrade to Terraform v0.12.24 or greater to work with this state`

**Comment by alencarlucas** [comment]
It still occurring with `0.12.24 - 0.12.25 `
Is there anyone looking at this? I think that kind of breaking changes should be avoided in minor versions releases.

**Comment by jltxwesley** [comment]
> In case anyone else needs it, I stumbled upon this in Terraform Cloud in `Settings > General`.
> 
> `The version of Terraform to use for this workspace. Upon creating this workspace, the latest version was selected and will be used until it is changed manually. It will not upgrade automatically.`
> 
> Changing this resolved my issue. Very inconvenient, but that's the solution.

Nice, this works perfectly.

**Comment by mikesigs** [comment]
I'm just here to throw my voice into this apparent echo chamber of an issue. This is super annoying! Can this please get fixed somehow?

**Comment by nikhils5501** [comment]
This happens when more than 1 person is running tf apply and their terraform binary version is not the same. You may have terraform `0.12.8` while the other guy may have `0.12.20`. In that case, once that person runs tf apply, the version on terraform remote state will be set as `0.12.20` and you will see the above error saying your version doesn't match the one existing on remote state.

To fix this, you can open the terraform remote state (its basically a json) and update the value of terraform version to a specific version you want. Then make everyone on your team use the same version terraform binary using the link: https://releases.hashicorp.com/terraform/

To avoid this, you can also pin the version on your tf code as 
```
terraform {
   required version = "=0.12.20"
}
```

**Comment by dkirrane** [comment]
Any workaround for his on Terraform Cloud?
In my Terraform Cloud workspace I have `Settings > General > Terraform Version > 0.12.24`

My Plan uses:
```
terraform {
  required_version = "= 0.12.24"
}
```

My TFC workspace State tab has no state: `This workspace currently has no states saved`

When I queue the plan I hit this:
`Error: state snapshot was created by Terraform v0.12.26, which is newer than current v0.12.24; upgrade to Terraform v0.12.26 or greater to work with this state`

The issue occurred because the initial workspace run that used `v0.12.26`. I swicthed to `0.12.24` and this started happening

**Comment by JeremyCraigMartinez** [comment]
@dkirrane I had this exact version discrepancy. I think since the versions are so close, they are probably on the same version of tfstate json. For this reason, I pulled the tfstate from S3 (storing state remotely) and simply changed the `"terraform_version": "0.12.26",` back to `"terraform_version": "0.12.24",` (second line down in the json), then reuploaded it to the same S3 key.

```json
{
  "version": 4,
  "terraform_version": "0.12.24",
  "serial": 10,
  ...
```

I think this is (very) ill-advised, but it seems to have done the trick for me 🤷‍♂️ . It's also reassuring that I was making this change in a non-production environment.

**Comment by rshbandar93** [comment]
delete your .tfstate in your bucket,
and try again to terraform init

**Comment by mike-dazn** [comment]
> delete your .tfstate in your bucket,
> and try again to terraform init

That is really poor advice and is a fundamental misunderstanding of what remote `.tfstate` is for.  Anyone who does this risks seriously damaging their infrastructure setup.

**Comment by abhisheksr01** [comment]
The behaviour is still the same with latest version :( :( 

Error refreshing state: state snapshot was created by Terraform v0.12.29, which is newer than current v0.12.28; upgrade to Terraform v0.12.29 or greater to work with this state

**Comment by Ayxan1** [comment]
The same problem...

Error refreshing state: state snapshot was created by Terraform v0.12.29, which is newer than current v0.12.28; upgrade to Terraform v0.12.29 or greater to work with this state

**Comment by zack-klein** [comment]
Same problem - I was able to fix this by going into the remote `.tfstate` and manually changing the `terraform_version`, but this feels super hacky. A cleaner solution to this would be fantastic!

At first glance, a simple solution to this could be to expose a command like `terraform state set-version` to the CLI that just updates the `.tfstate` file for the user? It's not ideal but I think it would make resolving this issue once it happens much safer.

**Comment by chuck-hilyard** [comment]
Running into the same issue as others.

**Comment by abcbharath** [comment]
Same problem with v0.12.28 version..
Error: Error loading state:
    state snapshot was created by Terraform v0.13.0, which is newer than current v0.12.28; upgrade to Terraform v0.13.0 or greater to work with this state

**Comment by iamaverrick** [comment]
im having same issue as @abcbharath

**Comment by julian-alarcon** [comment]
Now I have this error with Terraform 0.13
`Error: state snapshot was created by Terraform v0.13.0, which is newer than current v0.12.29; upgrade to Terraform v0.13.0 or greater to work with this state`

**Comment by douglasnaphas** [comment]
The impact is more severe when you have gone from Terraform v0.12.x to v0.13.0 using Terraform Cloud, and want to fall back to Terraform v0.12.x.

## Why I need to fall back
I upgraded to Terraform v0.13.0 by picking v0.13.0 in Terraform Cloud Settings. I got a clean plan output, but the apply step fails because of the issue I've described [on the forum](https://discuss.hashicorp.com/t/unknown-provider-nested-provider-error-on-terraform-cloud/12893): Terraform Cloud says `unknown provider "registry.terraform.io/-/aws"`.

The discussion on https://github.com/hashicorp/terraform/pull/25334 suggests that the error I'm hitting has to do with Terraform v0.13.0 features, so I need to fall back to v0.12.29.

## The workarounds don't work for Terraform Cloud
The workarounds suggested above, of selecting a new Terraform version in Terraform Cloud Settings or of manually editing my state file, do not help. The problem is that my state file says `"terraform_version": "0.13.0"`. Because my state file is stored in Terraform Cloud, I cannot edit it.

I don't know of any CLI commands for state management, like `terraform state rm`, that are able to manipulate the state file's `terraform_version`.

**Comment by estecker** [comment]
I had a similar issue when I accidentally pushed a 0.12 state with Terraform 0.13 in Terraform Cloud. That automatically set the version in the state to 0.13. I could not push an old state with 0.12 because it was older than 0.13. I was able to fix that problem via the method described here: https://support.hashicorp.com/hc/en-us/articles/360041299873

**Comment by abhineetraj** [comment]
Still having the same problem between sub-versions 0.12.28 and 0.12.26. This needs to be handled gracefully.

`Error: state snapshot was created by Terraform v0.12.28, which is newer than current v0.12.26; upgrade to Terraform v0.12.28 or greater to work with this state`

**Comment by dogzzdogzz** [comment]
Having same problem when trying 0.13, we have several individual environments (tsfstate) and we use ```data.terraform_remote_state``` to import some data from another environment. But It's difficult for us to done the 0.13 upgrade for all environments at the same time.

**Comment by wvxavier** [comment]
Having the same issue when imported resources from a module that was on version **0.13.0** to another one on version **0.13.5**

`Initializing the backend...
Error refreshing state: state snapshot was created by Terraform v0.13.5, which is newer than current v0.13.0; upgrade to Terraform v0.13.5 or greater to work with this state`

**Comment by nikhilo** [comment]
In a pretty 💩 situation right now. I created a new workspace and it automatically chose 0.14.0 on the very first plan. All the resourced showed this error.
```
Error: Unsupported Terraform Core version

  on .terraform/modules/rds_cluster_aurora_postgres.dns_master.this/versions.tf line 2, in terraform:
   2:   required_version = ">= 0.12.0, < 0.14.0"

Module module.rds_cluster_aurora_postgres.module.dns_master.module.this (from
git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2)
does not support Terraform version 0.14.0. To proceed, either choose another
supported Terraform version or update this version constraint. Version
constraints are normally set for good reason, so updating the constraint may
lead to other errors or unexpected behavior.
```
Note that this was from the very first plan.
So, I tried to downgrade the version to 0.13.5
And it complains that,
```
Error: state snapshot was created by Terraform v0.14.0, which is newer than current v0.13.5; upgrade to Terraform v0.14.0 or greater to work with this state
```

There is no state file for my workspace, so I don't even know what to revert at this point.

Weirdest part is, I even deleted the workspace and recreated it. Set the version to 0.13.5 before running the first plan. And it still complains about the `state snapshot was created by Terraform v0.14.0, which is newer than current v0.13.5`

**Comment by Sytten** [comment]
Yeah some weird errors here too with GCP provider and 0.14.0 https://github.com/hashicorp/terraform-provider-google/issues/7945, but I cant downgrade...

**Comment by nikhilo** [comment]
To clarify the issue I mentioned earlier, the workspace I was creating refers to outputs from another workspace which was mistakenly created with 0.14.0. So that's why even when I recreated my workspace with 0.13.5, it was showing the `state snapshot was created by Terraform v0.14.0` error. On recreating the other workspace with 0.13.5, the intended workspace is now working ok with 0.13.5.

**Comment by anagarjunr** [comment]
this issue still exists and is very annoying

using 
- terraform version `0.14.0` 
- remote backend -> terraform cloud (using local exec mode instead of remote)

getting this error : `Failed to load state: Terraform 0.14.0 does not support state version 4, please update.`

while the same version 4 works for other resources in another tf-workspaces

**Comment by dallinwright** [comment]
Extremely weird behavior here as well. On MacOS terraform applied with version 0.14.2 just fine, on Ubuntu the error is present:

`Error refreshing state: state snapshot was created by Terraform v0.14.2, which is newer than current v0.13.5; upgrade to Terraform v0.14.2 or greater to work with this state`

**Comment by acidprime** [comment]
If it helps anyone else, I found an interesting corner case thats confusing due to the message displayed. I was in the process of upgrading some dependant terraform configurations (lambdas) and they use remote_state.tf. I notice that I was getting this message , which I thought was part of the upgrade but it was in fact a chick before the egg issue with remote_state because my current terraform version was trying to read remote state from an already upgraded version, it caused this error message , though to me it was not very clear thats where this was coming from

**Comment by giom-l** [comment]
Hit this issue today also
Upgraded from 0.13.4 to 0.14.4. 
One of my stack showed lots of drifts, so I wanted to rollback to 0.13.4, but also getting 
`Error: state snapshot was created by Terraform v0.14.4, which is newer than current v0.13.4; upgrade to Terraform v0.14.4 or greater to work with this state`

However, the state version is 0.13.4, not updated since last december (s3 backend)
I removed every cache files that could exist locally, I still don't understand where this state snapshot come from....

ATM, I have to leave it as is or accept to recreate this part of my infrastructure (as there is lots of recreate needed...)

If anyone has an idea where this snapshot version could come from, I'm interested.

**Comment by commarla** [comment]
@giom-l maybe (as @acidprime suggest) you have a data source `terraform_remote_state` already upgraded to TF 0.14.4. Terraform displays this message while trying to read a remote state within a data source (in addition to his own remote state)

**Comment by mmell** [comment]
I hit this issue too. 

One of the `data.terraform_remote_state` modules was on `0.14.2` but the root module was on `0.12.29`. 

I was able to remove the reference to the data.terraform_remote_state and carry on.

**Comment by isaacphi** [comment]
Ran into this today for my state stored in Terraform cloud, even though **my execution mode was set to Local**, and the version showed in my state file was the same as the version I'm running locally (v0.14.4).
Solution was to go to Settings -> General, enable Remote execution mode, select the matching version, save, then enable local execution mode again.

**Comment by bitnahian** [comment]
Same issues here. We use a remote GCS-backend for our state. Currently facing this issue:

```
Failed to load state: state snapshot was created by Terraform v0.14.3, which is newer than current v0.13.5; upgrade to Terraform v0.14.3 or greater to work with this state
```

**Comment by scarolan** [comment]
Please fix this way-to-easy-to-trigger footgun.

**Comment by mt-inside** [comment]
I have a similar issue, looking to help people who hit it.
When running `terraform taint` I get
`Failed to load state: Remote workspace Terraform version "0.12.25" does not match local Terraform version "0.14.4"`

I'm using local execution (of course), and the fix, hear me out...
* Go to Terraform Cloud -> <workspace> -> Settings -> General
* Change `Execution Mode` to `Remote`
* This makes `Terraform Version` visible...
* Change it to match your local version
* Change `Execution Mode` back to `Local`
* Hit `Save Settings`
* Fixed! 🙄

**Comment by qwerty1979bg** [comment]
@mt-inside , 
This particular bug was fixed by #27498 in [Terraform v0.14.5](https://github.com/hashicorp/terraform/releases/tag/v0.14.5)

**Comment by lado936** [comment]
@qwerty1979bg  it still happening to me,

`Failed to load state: state snapshot was created by Terraform v0.14.6, which is newer than current v0.13.6; upgrade to Terraform v0.14.6 or greater to work with this state`

**Comment by qwerty1979bg** [comment]
@lado936 I suspect that your case is not the same as the one described by mt-inside.

This thread has been running for a while and people have mixed a few separate issues.

If you are using Terraform Cloud, your best bet is to open a case with support, so they can help you with your particular error / issue:
https://support.hashicorp.com/hc/en-us

If you are using Terraform CLI, you can start a thread in the community:
https://www.terraform.io/community.html

If you are sure this is actually related to the original poster's issue, please provide additional details.

**Comment by lado936** [comment]
@qwerty1979bg  its definitely Terraform CLI, i am referencing other module inside terraform which is in fact ran by terraform 0.14.6, i am using 0.13.6 and have the error showed up, as referenced module is ran by 0.14.6 i cant use it inside my module.

**Comment by simov** [comment]
Not sure if this is even a bug in my case, but I was also stuck with a shared remote state on 0.14, where my project was still on 0.12 and I had to migrate it to 0.13 first.

As usual I did a plan using 0.13 locally, but before that instead of patching the remote state directly (on S3), I decided to pull it locally and patch my shared state source to use it as a local backend instead:

```tf
data "terraform_remote_state" "shared" {
  backend = "local"
  config = {
    path = "/home/.../${var.environment}.terraform.json"
  }
}
```

This is just a variation of some of the previous comments, but I found it safer to do this operation locally instead of patching the actual remote state that might as well be used by someone else in that moment.

**Comment by idavydiak** [comment]
I have found working solution for Terraform Enterprise here: https://support.hashicorp.com/hc/en-us/articles/360041299873

Error was: `state snapshot was created by Terraform v0.13.6, which is newer than current v0.12.29; upgrade to Terraform v0.13.6 or greater to work with this state`

**Comment by figaw** [comment]
+1 for adding a `-upgrade` flag to `terraform init` to explicitly upgrade the version of the state, or fail with a warning similar to
```
Error: state snapshot was created by Terraform v0.12.29, which is older than current v0.13.5; use v0.12.29 or use `-upgrade` to upgrade to Terraform v0.13.5 or greater to work with this state
```

**Comment by yegorski** [comment]
Just hit this when going form 0.11.14 to 0.12.29. The error was 

> Error: state snapshot was created by Terraform v0.13.6, which is newer than current v0.12.29; upgrade to Terraform v0.13.6 or greater to work with this state

The issue was that the repo I was upgrading pulled in a 0.13.6 `terraform_remote_state` and that's what the error was really aobut.

**Comment by mikemartin1090** [comment]
@yegorski Thank you for pointing that out. My 12.25 workspace is pulling `terraform_remote_state` from a 12.26 workspace. What did you end up doing to resolve the issue?

**Comment by yegorski** [comment]
I removed data "terraform_remote_state" block that was pulling TF state of a projects that's on a version higher than 0.12. This was a big project that was pulling in and referencing state from multiple other projects.

**Comment by jslusher** [comment]
I just ran into this on an upgrade from `0.12.16` to `0.13.6` using s3 as my remote state storage. I have a lot of RDS instances and I got [this error](https://github.com/hashicorp/terraform-provider-aws/issues/4597) and terraform failed midway through the apply as a result. I had planned on backing out of the upgrade and so I tried a plan with my previous version and I ran into this issue. I then decided to try [this](https://github.com/hashicorp/terraform/issues/23290#issuecomment-667528553) method and edit the tf version in the `.tfstate` file and although the error went away it also now doesn't see anything in the state and it wants to create everything. At this point I'm just going to push forward since I don't want to know what happens if I try to apply that plan. 
```
Plan: 53 to add, 0 to change, 0 to destroy.
```

**Comment by Joeltrane** [comment]
Has anyone tried using `-lock=false` to their `terraform apply` and/or `terraform destroy` commands?

I had a similar issue going from version  `0.13.5` to `1.0.2`. Including `-lock=false` was able to allow me to at least gracefully destroy everything and start over, but that was what I wanted to do. It might work on an `apply` ..

**Comment by Vincenius** [comment]
The solution for me was to download a previous version of the state from s3 and re-upload it to replace the one with the wrong version
