### ISSUE TITLE
Additional output ignored

### ISSUE THREAD

**Issue by pikeas** [hashicorp/terraform#2598]
I've added an additional output to my outputs.tf file. When I then run `terraform apply` , the new output is not displayed. It's also not found by `terraform output new_output_name`.

Possible fix: Whenever the state file is updated, outputs should also be refreshed.

**Comment by mitchellh** [comment]
Can you show us your config (or the relevant parts) and the output you added? Also, if you can add a debug log (from `TF_LOG=1` being set) via gist, that would be much appreciated as well.

We have tests around this and I just tried it locally and it worked fine. So I'm assuming there is some edge case going on here we're not seeing.

**Comment by pikeas** [comment]
Outputs.tf.json (`bastion_public_ip` is new):

```
{
  "output": {
    "vpc_id": {
      "value": "${aws_vpc.main.id}"
    },
    "bastion_public_ip": {
      "value": "${aws_instance.bastion_nat.bastion_public_ip}"
    }
  }
}
```
Truncated vpc.tf.json:

```
{
  "resource": {
    <snip>
    "aws_instance": {
      "bastion_nat": {
        "ami": "${lookup(var.nat_amis, var.region)}",
        "instance_type": "t2.micro",
        "subnet_id": "${aws_subnet.public.0.id}",
        "source_dest_check": false,
        "key_name": "${aws_key_pair.bastion.key_name}",
        "tags": {
          "Name": "${var.prefix}-bastion-nat"
        }
      }
    }
  }
}
```

Apply output for `terraform apply <folder>`:
```
<everything refreshes state>

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

  vpc_id = vpc-f0d8d395
```

TF_LOG=1 full output: https://gist.github.com/pikeas/6a09a8dfd5e8c81c58d1

**Comment by pikeas** [comment]
Additional clue: I blew away (`terraform destroy`) and recreated this stack for an unrelated reason, and the problem persists.

So, `output` doesn't like being a hash? If I pass a list of hashes instead, `terraform apply` still runs, but doesn't output anything at the end.

**Comment by attenda-pjaquenoud** [comment]
I'm hitting similar if not the same issue.   I've got a top level "environment" that calls modules.  Adding a new output to a module doesn't seem to be recognised but adding a new output to the top level environment does.

**Comment by hazim1093** [comment]
Facing a similar issue with terraform 0.7.3. 
Output was available after apply because I had accessed it in another module, but after some time when I was trying to access the output in another module it was missing.  
I'm suspecting it to be caused by refresh ? as there were a lot of refreshes done in between.

Seems related to this https://github.com/hashicorp/terraform/issues/2465 as well

Possible workaround: Refresh the modules with output, every time before applying modules which use that output. ( It seems to be working well for me up till now)

**Comment by mitchellh** [comment]
As far as I can tell all use cases in this issue have been addressed and resolved in 0.8 (now in RC). If any specific examples still are broken, please open a new issue. Thank you!

**Comment by voroniys** [comment]
@mitchellh before stating it is solved it would be good to at least test if it is really so. You close #9287 as a duplicate of this one and close this one while #9287 is still not solved.

**Comment by sriraja53** [comment]
I am still facing this issue in below terraform version

I am using s3 as backed 

Terraform v0.11.10
+ provider.aws v2.12.0
+ provider.http v1.1.1
+ provider.null v2.1.2
+ provider.template v2.1.2
