### ISSUE TITLE
Terraform provider plugin cache not working 

### ISSUE THREAD

**Issue by a18-kaushik** [hashicorp/terraform#32936]
### Terraform Version

```shell
1.0.10
```

### Terraform Configuration Files

```
plugin_cache_dir   = "C:/Users/a18.kaushik/AppData/Roaming/terraform.d/plugin-cache"
```

### Debug Output

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding latest version of hashicorp/aws...
2023-03-29T10:22:55.997+0530 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2023-03-29T10:22:55.997+0530 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
2023-03-29T10:22:57.533+0530 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/aws/versions
2023-03-29T10:22:57.534+0530 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/aws/versions
2023-03-29T10:22:58.963+0530 [TRACE] providercache.fillMetaCache: scanning directory .terraform\providers
2023-03-29T10:22:58.963+0530 [TRACE] getproviders.SearchLocalDirectory: failed to resolve symlinks for .terraform\providers: CreateFile .terraform\providers: The system cannot find the file specified.
2023-03-29T10:22:58.963+0530 [TRACE] providercache.fillMetaCache: error while scanning directory .terraform\providers: cannot search .terraform\providers: CreateFile .terraform\providers: The system cannot find the file specified.
2023-03-29T10:22:58.963+0530 [TRACE] providercache.fillMetaCache: scanning directory C:/Users/a18.kaushik/AppData/Roaming/terraform.d/plugin-cache
- Using hashicorp/aws v4.60.0 from the shared cache directory
2023-03-29T10:22:58.965+0530 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/aws v4.60.0 for windows_amd64 at C:\Users\a18.kaushik\AppData\Roaming\terraform.d\plugin-cache\registry.terraform.io\hashicorp\aws\4.60.0\windows_amd64
2023-03-29T10:22:58.965+0530 [TRACE] providercache.fillMetaCache: including C:\Users\a18.kaushik\AppData\Roaming\terraform.d\plugin-cache\registry.terraform.io\hashicorp\aws\4.60.0\windows_amd64 as a candidate package for registry.terraform.io/hashicorp/aws 4.60.0
2023-03-29T10:22:58.968+0530 [TRACE] providercache.Dir.LinkFromOtherCache: linking registry.terraform.io/hashicorp/aws v4.60.0 from existing cache C:/Users/a18.kaushik/AppData/Roaming/terraform.d/plugin-cache/registry.terraform.io/hashicorp/aws/4.60.0/windows_amd64 to .terraform/providers/registry.terraform.io/hashicorp/aws/4.60.0/windows_amd64
╷
│ Error: Failed to install provider from shared cache
│
│ Error while importing hashicorp/aws v4.60.0 from the shared cache directory: failed to create directory
│ C:\Users\a18.kaushik\Desktop\.terraform\providers\registry.terraform.io\hashicorp\aws\4.60.0\windows_amd64:
│ mkdir
│ C:\Users\a18.kaushik\Desktop\.terraform\providers\registry.terraform.io\hashicorp\aws\4.60.0\windows_amd64:
│ Cannot create a file when that file already exists..
╵

### Expected Behavior

terraform init execute successfully with cache provider

### Actual Behavior

Error: Failed to install provider
│
│ Error while installing hashicorp/aws v4.60.0: failed to create directory
│ C:\Users\a18.kaushik\Desktop\.terraform\providers\registry.terraform.io\hashicorp\aws\4.60.0\windows_amd64:
│ mkdir
│ C:\Users\a18.kaushik\Desktop\.terraform\providers\registry.terraform.io\hashicorp\aws\4.60.0\windows_amd64:
│ Cannot create a file when that file already exists.

### Steps to Reproduce

1. make terraform.rc file with above configuration file settings
2. create "plugin-cache" folder in "C:\Users\a18.kaushik\AppData\Roaming\terraform.d" 
3. run terraform init

### Additional Context

followed documentation for provider plugin cache : https://developer.hashicorp.com/terraform/cli/config/config-file#provider-installation

**Comment by jbardin** [comment]
Hi @a18-kaushik,

Can you please verify that the behavior is the same on a current release of Terraform? Some behaviors have changed and bugs have been fixed since the v1.0 releases.

Thanks!

**Comment by a18-kaushik** [comment]
i tried with version **1.4.2** but the problem persists

debug logs:

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding hashicorp/aws versions matching "4.60.0"...
2023-03-30T09:45:56.870+0530 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2023-03-30T09:45:56.870+0530 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json2023-03-30T09:45:59.667+0530 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/aws/versions
2023-03-30T09:45:59.668+0530 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/aws/versions
2023-03-30T09:46:01.064+0530 [TRACE] providercache.fillMetaCache: scanning directory .terraform\providers
2023-03-30T09:46:01.065+0530 [TRACE] getproviders.SearchLocalDirectory: failed to resolve symlinks for .terraform\providers: CreateFile .terraform\providers: The system cannot find the file specified.
2023-03-30T09:46:01.065+0530 [TRACE] providercache.fillMetaCache: error while scanning directory .terraform\providers: cannot search .terraform\providers: CreateFile .terraform\providers: The system cannot find the file specified.
2023-03-30T09:46:01.066+0530 [TRACE] providercache.fillMetaCache: scanning directory C:/Users/a18.kaushik/AppData/Roaming/terraform.d/plugin-cache
2023-03-30T09:46:01.070+0530 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/aws v4.60.0 for windows_amd64 at C:\Users\a18.kaushik\AppData\Roaming\terraform.d\plugin-cache\registry.terraform.io\hashicorp\aws\4.60.0\windows_amd64
2023-03-30T09:46:01.071+0530 [TRACE] providercache.fillMetaCache: including C:\Users\a18.kaushik\AppData\Roaming\terraform.d\plugin-cache\registry.terraform.io\hashicorp\aws\4.60.0\windows_amd64 as a candidate package for registry.terraform.io/hashicorp/aws 4.60.0
2023-03-30T09:46:01.071+0530 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/aws/4.60.0/download/windows/amd64
2023-03-30T09:46:01.071+0530 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/aws/4.60.0/download/windows/amd64
2023-03-30T09:46:04.410+0530 [DEBUG] GET https://releases.hashicorp.com/terraform-provider-aws/4.60.0/terraform-provider-aws_4.60.0_SHA256SUMS
2023-03-30T09:46:04.410+0530 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-aws/4.60.0/terraform-provider-aws_4.60.0_SHA256SUMS
2023-03-30T09:46:06.584+0530 [DEBUG] GET https://releases.hashicorp.com/terraform-provider-aws/4.60.0/terraform-provider-aws_4.60.0_SHA256SUMS.72D7468F.sig
2023-03-30T09:46:06.585+0530 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-aws/4.60.0/terraform-provider-aws_4.60.0_SHA256SUMS.72D7468F.sig
- Installing hashicorp/aws v4.60.0...
2023-03-30T09:46:06.985+0530 [TRACE] providercache.Dir.InstallPackage: installing registry.terraform.io/hashicorp/aws v4.60.0 from https://releases.hashicorp.com/terraform-provider-aws/4.60.0/terraform-provider-aws_4.60.0_windows_amd64.zip
2023-03-30T09:46:06.986+0530 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-aws/4.60.0/terraform-provider-aws_4.60.0_windows_amd64.zip
2023-03-30T09:58:53.100+0530 [DEBUG] Provider signed by 34365D9472D7468F HashiCorp Security (hashicorp.com/security) <security@hashicorp.com>
2023-03-30T10:03:49.155+0530 [TRACE] providercache.fillMetaCache: scanning directory C:/Users/a18.kaushik/AppData/Roaming/terraform.d/plugin-cache
2023-03-30T10:03:49.158+0530 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/aws v4.60.0 for windows_amd64 at C:\Users\a18.kaushik\AppData\Roaming\terraform.d\plugin-cache\registry.terraform.io\hashicorp\aws\4.60.0\windows_amd64
2023-03-30T10:03:49.158+0530 [TRACE] providercache.fillMetaCache: including C:\Users\a18.kaushik\AppData\Roaming\terraform.d\plugin-cache\registry.terraform.io\hashicorp\aws\4.60.0\windows_amd64 as a candidate package for registry.terraform.io/hashicorp/aws 4.60.0
2023-03-30T10:03:49.158+0530 [TRACE] providercache.Dir.LinkFromOtherCache: linking registry.terraform.io/hashicorp/aws v4.60.0 from existing cache C:/Users/a18.kaushik/AppData/Roaming/terraform.d/plugin-cache/registry.terraform.io/hashicorp/aws/4.60.0/windows_amd64 to .terraform/providers/registry.terraform.io/hashicorp/aws/4.60.0/windows_amd64
╷
│ Error: Failed to install provider
│
│ Error while installing hashicorp/aws v4.60.0: failed to create directory
│ C:\Users\a18.kaushik\Desktop\.terraform\providers\registry.terraform.io\hashicorp\aws\4.60.0\windows_amd64:
│ mkdir
│ C:\Users\a18.kaushik\Desktop\.terraform\providers\registry.terraform.io\hashicorp\aws\4.60.0\windows_amd64:
│ Cannot create a file when that file already exists.

**Comment by a18-kaushik** [comment]
@jbardin did you get a chance to look into this? 
thanks

**Comment by yongzhang** [comment]
I upgraded from v1.3.x to v1.4.x, looks like `install from caching` no longer works, or at least no longer works as expected.
I have multiple stack folders using the same providers, `terraform init` installs all of the providers in the first stack folder, but it still downloads the same in the following folders but not from cache.

**Comment by jbardin** [comment]
@yongzhang, this issue was reported with a version of v1.0, so is not something which would have changed between v1.3 and v1.4.

**Comment by jbardin** [comment]
@a18-kaushik, The error is a Windows error from linking the provider files. It will take some time to reproduce and investigate what exactly is failing on that platform.

**Comment by a18-kaushik** [comment]
@jbardin okay noted!

**Comment by phyber** [comment]
I believe I have this issue on Linux (amd64) too with Terraform 1.4.6. Terraform will scan my plugin-cache, find appropriate versions of the (in this case) AWS provider, and proceed to re-download it anyway. There seem to be no logs in the `TF_LOG=TRACE` that say why it decided to redownload the provider.

It may also be re-downloading other providers constantly too, but since they're much smaller it's harder to notice.

The plugin cache used to work correctly, I'm unsure when it broke, but it's definitely been months for me at this point.

**Comment by fyqtian** [comment]
version 1.5.2  on Mac(amd64)  is same behavior
`Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 1.0.0"...
2023-07-04T13:52:05.730+0800 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2023-07-04T13:52:05.730+0800 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
2023-07-04T13:52:06.487+0800 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/aws/versions
2023-07-04T13:52:06.487+0800 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/aws/versions
2023-07-04T13:52:07.012+0800 [TRACE] providercache.fillMetaCache: scanning directory .terraform/providers
2023-07-04T13:52:07.012+0800 [TRACE] getproviders.SearchLocalDirectory: failed to resolve symlinks for .terraform/providers: lstat .terraform/providers: no such file or directory
2023-07-04T13:52:07.012+0800 [TRACE] providercache.fillMetaCache: error while scanning directory .terraform/providers: cannot search .terraform/providers: lstat .terraform/providers: no such file or directory
2023-07-04T13:52:07.012+0800 [TRACE] providercache.fillMetaCache: scanning directory /Users/fanv/.terraform.d/plugin-cache
2023-07-04T13:52:07.015+0800 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/archive v2.4.0 for darwin_amd64 at /Users/fanv/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/archive/2.4.0/darwin_amd64
2023-07-04T13:52:07.016+0800 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/aws v4.30.0 for darwin_amd64 at /Users/fanv/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/aws/4.30.0/darwin_amd64
2023-07-04T13:52:07.017+0800 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/aws v4.54.0 for darwin_amd64 at /Users/fanv/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/aws/4.54.0/darwin_amd64
2023-07-04T13:52:07.017+0800 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/aws v5.6.2 for darwin_amd64 at /Users/fanv/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/aws/5.6.2/darwin_amd64
2023-07-04T13:52:07.018+0800 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/random v3.5.1 for darwin_amd64 at /Users/fanv/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/random/3.5.1/darwin_amd64
2023-07-04T13:52:07.018+0800 [TRACE] providercache.fillMetaCache: including /Users/fanv/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/archive/2.4.0/darwin_amd64 as a candidate package for registry.terraform.io/hashicorp/archive 2.4.0
2023-07-04T13:52:07.018+0800 [TRACE] providercache.fillMetaCache: including /Users/fanv/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/aws/4.30.0/darwin_amd64 as a candidate package for registry.terraform.io/hashicorp/aws 4.30.0
2023-07-04T13:52:07.018+0800 [TRACE] providercache.fillMetaCache: including /Users/fanv/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/aws/4.54.0/darwin_amd64 as a candidate package for registry.terraform.io/hashicorp/aws 4.54.0
2023-07-04T13:52:07.018+0800 [TRACE] providercache.fillMetaCache: including /Users/fanv/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/aws/5.6.2/darwin_amd64 as a candidate package for registry.terraform.io/hashicorp/aws 5.6.2
2023-07-04T13:52:07.018+0800 [TRACE] providercache.fillMetaCache: including /Users/fanv/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/random/3.5.1/darwin_amd64 as a candidate package for registry.terraform.io/hashicorp/random 3.5.1
2023-07-04T13:52:07.018+0800 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/aws/5.6.2/download/darwin/amd64
2023-07-04T13:52:07.018+0800 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/aws/5.6.2/download/darwin/amd64
2023-07-04T13:52:07.540+0800 [DEBUG] GET https://releases.hashicorp.com/terraform-provider-aws/5.6.2/terraform-provider-aws_5.6.2_SHA256SUMS
2023-07-04T13:52:07.540+0800 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-aws/5.6.2/terraform-provider-aws_5.6.2_SHA256SUMS
2023-07-04T13:52:08.263+0800 [DEBUG] GET https://releases.hashicorp.com/terraform-provider-aws/5.6.2/terraform-provider-aws_5.6.2_SHA256SUMS.72D7468F.sig
2023-07-04T13:52:08.263+0800 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-aws/5.6.2/terraform-provider-aws_5.6.2_SHA256SUMS.72D7468F.sig
- Installing hashicorp/aws v5.6.2...
2023-07-04T13:52:08.432+0800 [TRACE] providercache.Dir.InstallPackage: installing registry.terraform.io/hashicorp/aws v5.6.2 from https://releases.hashicorp.com/terraform-provider-aws/5.6.2/terraform-provider-aws_5.6.2_darwin_amd64.zip
2023-07-04T13:52:08.432+0800 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-aws/5.6.2/terraform-provider-aws_5.6.2_darwin_amd64.zip`

**Comment by fyqtian** [comment]
I believe that if the .terraform.lock.hcl file is absent, local caching will not be utilized.

https://github.com/hashicorp/terraform/blob/v1.4.6/internal/providercache/installer.go#L387-L398

**Comment by magodo** [comment]
Same thing happens to me (on Linux), where I have to use `plugin_cache_may_break_dependency_lock_file = true` to make the cache to work. This isn't an issue back in the v1.3.x.

**Comment by tnc-tschmidt** [comment]
Same. Essentially if the there is no lock file it will always download from upstream and not respect the plugin_cache. For me setting **plugin_cache_may_break_dependency_lock_file** does not help and it still redownloads it.

My unfortunate work around is to pin the aws provider version and copy in a .terraform.lock.hcl file with the hashes. Whicht seems like this is expected behavior but I don't understand the reasoning behind this decision. 
```
				// An existing cache entry is only an acceptable choice
				// if there is already a lock file entry for this provider
				// and the cache entry matches its checksums.
				//
				// If there was no lock file entry at all then we need to
				// install the package for real so that we can lock as complete
				// as possible a set of checksums for all of this provider's
				// packages.
```

**Comment by alxndr13** [comment]
> Same thing happens to me (on Linux), where I have to use `plugin_cache_may_break_dependency_lock_file = true` to make the cache to work. This isn't an issue back in the v1.3.x.

can confirm. Only accesses the local plugin cache if I set the environment variable.

```bash
Terraform v1.7.3
on linux_amd64
```

**Comment by jakauppila** [comment]
Just to chime in on our use-case.

We’ve built a Terraform container for our CI/CD pipelines where we pre-populate the provider cache with required versions. This approach gives us consistent, reproducible builds while minimizing network dependencies and improving execution times.

```hcl
plugin_cache_may_break_dependency_lock_file = true
disable_checkpoint = true

provider_installation {
  direct {
    exclude = ["registry.terraform.io/*/*"]
  }
  filesystem_mirror {
    path = "/jenkins/utilities/terraform/filesystem_mirror"
  }
  network_mirror {
    url = "https://artifactory.contoso.com/artifactory/api/terraform/terraform-registry/providers/"
  }
}
```
### Issue:

Even with the correct provider versions cached and matching the version constraints in our Terraform configs, Terraform still queries the network mirror (e.g., Artifactory) during `terraform init`. For example:

- Our Terraform config specifies the AWS provider as `~> 5.0`.
- We have `5.82.1` cached locally, which satisfies this constraint.
- However, Terraform still attempts to pull `5.85.0` from the network mirror.
- If we explicitly pin the version to `= 5.82.1`, Terraform uses the cached version correctly.

This leads to:

- Unnecessary network calls despite having compatible versions locally.
- Slower CI/CD runs due to external fetches.

### Desired Behavior:
Terraform should prioritize the local filesystem mirror when version constraints are satisfied, only falling back to the network mirror if:

1. The provider version is missing locally.
2. The local version doesn’t meet the specified constraints.

### Proposed Solutions:

#### 1. Priority Option in `.terraformrc`
Introduce a priority field to explicitly control the order of provider resolution.

```hcl
provider_installation {
  filesystem_mirror {
    path    = "/path/to/prepopulated/cache"
    include = ["registry.terraform.io/*/*"]
    priority = 1  # Highest priority: Use if version constraints are met
  }

  network_mirror {
    url     = "https://artifactory.contoso.com/api/terraform/terraform-registry/providers/"
    include = ["registry.terraform.io/*/*"]
    priority = 2  # Fallback if filesystem mirror doesn't satisfy constraints
  }

  direct {
    exclude  = ["registry.terraform.io/*/*"]
    priority = 3  # Lowest priority, excluded unless explicitly needed
  }
}
```

#### 2. Configurable via CLI Flag or Environment Variable

Introduce a CLI flag and corresponding environment variable to prefer the filesystem mirror when version constraints are satisfied:

- CLI Flag Example:
```bash
terraform init --prefer-filesystem-mirror
```
- Environment Variable Example:
```bash
export TF_PREFER_FILESYSTEM_MIRROR=true
terraform init
```

This allows flexible, per-execution control without modifying `.terraformrc`, making it ideal for dynamic CI/CD environments.

### Alternative Workarounds:

#### Two-Step Init Process:

As a workaround, I've considered running `terraform init` with the `-plugin-dir` flag pointing to our pre-populated cache. If Terraform encounters an error due to unmet version constraints, we’d fallback to a second `terraform init` without the `-plugin-dir` to allow network retrieval.

Example of the error when constraints aren’t met:

> Error: Failed to query available provider packages
> 
> Could not retrieve the list of available versions for provider hashicorp/aws: no available releases match the given constraints 5.85.0

While this approach would technically achieve the desired behavior, it’s inefficient and adds unnecessary complexity to our CI/CD pipelines. A native solution through configuration or flags would be far more elegant and maintainable.

#### Persistent Cache Volume (e.g., NFS):

Another option is to attach a persistent cache volume (such as an NFS share) to the container executions, allowing providers to be shared across runs. However, the [Terraform documentation](https://developer.hashicorp.com/terraform/cli/config/config-file#provider-installation) notes:

> The plugin cache directory is not guaranteed to be concurrency safe. The provider installer’s behavior in environments with multiple terraform init calls is undefined.

Due to this, it's unclear how Terraform would handle concurrent executions in a CI/CD environment, potentially introducing race conditions or cache corruption.

**Comment by dsa0x** [comment]
Hello @jakauppila. Thank you for the reproduction steps. Did you have the dependency lock file of the downloaded provider (5.82.1) in the root directory of your configuration steps? Presently, if you have no lock file, terraform will always redownload the provider, so that it can generate a more complete checksum for future runs. 

Also, Is your issue about the API calls that are being made to the registry, even though they do not redownload the providers, or are you actually seeing the providers getting redownloaded? I used the first script in your gist, and subsequent runs seem to be using the shared cache (provided that the lock file is persisted)

**Comment by jakauppila** [comment]
> Hello @jakauppila. Thank you for the reproduction steps. Did you have the dependency lock file of the downloaded provider (5.82.1) in the root directory of your configuration steps? Presently, if you have no lock file, terraform will always redownload the provider, so that it can generate a more complete checksum for future runs. 
> 
> If you do have a lock file, Is your issue about the API calls that are being made to the registry, even though they do not redownload the providers, or are you actually seeing the providers getting redownloaded? I used the first script in your gist, and subsequent runs seem to be using the shared cache (provided that the lock file is persisted)

No lock file defined, but I do have 'plugin_cache_may_break_dependency_lock_file' set.

Ideally there could be a way to tell Terraform to utilize the providers currently in the cache if they satisfy the version constraints defined in configuration and only reach out if the constraints are not met.

**Comment by dsa0x** [comment]
Thank you for sharing, and yes `plugin_cache_may_break_dependency_lock_file` has a different use, so it is not the solution here.

**Comment by ricardbejarano** [comment]
Another alternative to @jakauppila's is to do [this](https://www.bejarano.io/terraform-overlayfs/), while concurrency safety of the Terraform plugin cache is fixed upstream.
