### ISSUE TITLE
Possible Bug in aws/s3_bucket provider populating the hosted_zone_id attribute

### ISSUE THREAD

**Issue by railsbros-dirk** [hashicorp/terraform#3334]
I want to create a S3 bucket enabled for 'Static Website Hosting' and creating a Route53 alias record for it. This is the part of my config to do so:

```
resource "aws_s3_bucket" "styleguide" {
  bucket = "styleguide.staging.fejo.sexy"
  acl = "public-read"

  website {
    index_document = "index.html"
    error_document = "error.html"
  }
}

resource "aws_route53_record" "styleguide" {
  zone_id = "${var.route53_fejo_sexy_zone_id}"
  name = "styleguide.staging.fejo.sexy"
  type = "A"

  alias {
    name = "${aws_s3_bucket.styleguide.website_domain}"
    zone_id = "${aws_s3_bucket.styleguide.hosted_zone_id}"
    evaluate_target_health = true
  }
}
```

Creating the bucket works as expected but the Route53 record resource fails with the following error (Searching for this didn't yielded any results so far):

```
aws_route53_record.styleguide: InvalidChangeBatch: amazon.security.AmzUidException: Encrypted token cannot be empty
```

It seems the `aws_s3_bucket`doesn't return any value for `hosted_zone_id`. I added the attribute to the output my config and it was empty. Finally adding the `zone_id` manually to the Terraform config made everything work. But obviously this is not what I wanted ;-)

I already found the issue #2210 which seemed to relate to this overall topic. I guess someone already tested this while working on the issue. Thus I don't know if I made something wrong in my config or if this is a real bug.

Thanks for helping out!

**Comment by AlexanderEkdahl** [comment]
Are you by any chance using eu-central-1 region? I've encountered the same error.

**Comment by railsbros-dirk** [comment]
Yes. I'm running in eu-central-1. sirry to mention this before.

**Comment by catsby** [comment]
Hey @railsbros-dirk – sorry for the silence here. I believe this issue is fixed now, as I'm not able to reproduce it. The fix should have been introduced in 0.6.2, so if you're still hitting this let me know.

I used this config to test, and things worked as expected:

```hcl
resource "aws_s3_bucket" "styleguide" {
  bucket = "styleguide.staging.tftesting.com"
  acl    = "public-read"

  website {
    index_document = "index.html"
    error_document = "error.html"
  }
}

resource "aws_route53_zone" "primary" {
  name = "tftesting.com"
}

resource "aws_route53_record" "styleguide" {
  zone_id = "${aws_route53_zone.primary.id}"
  name    = "styleguide.staging.tftesting.com"
  type    = "A"

  alias {
    name                   = "${aws_s3_bucket.styleguide.website_domain}"
    zone_id                = "${aws_s3_bucket.styleguide.hosted_zone_id}"
    evaluate_target_health = true
  }
}

output "hosted" {
  value = "${aws_s3_bucket.styleguide.hosted_zone_id}"
}
```

**Comment by railsbros-dirk** [comment]
Sorry, only had the chance to test this today. I still don't get a `hosted_zone_id`:

```
~ module.styleguide.aws_route53_record.styleguide
    alias.1470388263.evaluate_target_health: "1" => "0"
    alias.1470388263.name:                   "s3-website.eu-central-1.amazonaws.com" => ""
    alias.1470388263.zone_id:                "Z21DNDUVLTQW6Q" => ""
    alias.909221137.evaluate_target_health:  "" => "1"
    alias.909221137.name:                    "" => "s3-website.eu-central-1.amazonaws.com"
    alias.909221137.zone_id:                 "" => ""
```

My config is the same as yours. What region do tested this in? I'm running in `eu-central-1`, maybe there is a problem with this..

**Comment by catsby** [comment]
Yep, found it, patch incoming..

**Comment by catsby** [comment]
Fix sent in https://github.com/hashicorp/terraform/pull/4236 , turns out we have a typo :frowning:

**Comment by railsbros-dirk** [comment]
Thanks for the fast fix. And damn those typos😊
