### ISSUE TITLE
Support Cloudflare r2 for storing Terraform state

### ISSUE THREAD

**Issue by maggie44** [hashicorp/terraform#33847]
### Terraform Version

```shell
1.5.6
```

### Use Cases

Cloudflare r2 storage is S3 API compatible, but the `s3` backend for storing Terraform state seems to be only compatible with Amazon AWS.

https://developers.cloudflare.com/r2/api/s3/api/

### Attempted Solutions

Tried using the S3 but it's not compatible. Thought changing the `endpoint` would do it, but the region field is compulsory. When adding in a random region it fails to authenticate with the Cloudflare endpoint.

**Comment by crw** [comment]
Thanks for this request!

**Comment by ioannidesalex** [comment]
Didn't find a working solution for Terraform 1.6+

**Comment by bestrocker221** [comment]
I am having the same problem, i also added
```
skip_requesting_account_id  = true
skip_metadata_api_check     = true
```

But now I get:
```
│ Error: Failed to save state
│ 
│ Error saving state: failed to upload state: operation error S3: PutObject,
│ https response error StatusCode: 501, RequestID: , HostID: , api error
│ NotImplemented: STREAMING-UNSIGNED-PAYLOAD-TRAILER not implemented
```

I could not find a workaround

**Comment by crw** [comment]
Terraform 1.6.x included an upgrade to the AWS SDK v2, (see the [release notes](https://github.com/hashicorp/terraform/releases/tag/v1.6.0)), and 1.6.3 will add a feature that should help with third-party, S3-"compatible" object stores. It may be worth re-testing with 1.6.3, although I do not specifically recognize the error specified above.

**Comment by bestrocker221** [comment]
I can confirm the error mentioned above (STREAMING-UNSIGNED-PAYLOAD-TRAILER) appears with many others s3 compatible providers, such as Cloudflare R2 for example.
State file and s3 cant really be used anymore at the moment.. will test out with 1.6.3 as soon as its out

**Comment by maggie44** [comment]
> > State file and s3 cant really be used anymore at the moment
> 
> To clarify for any future reader of this issue, AWS S3 can be used as a state file backend now. "S3-compatible" services from non-AWS vendors appear to be having trouble keeping up with compatibility, but hopefully the fixes made to the S3 backend by our AWS provider team to workaround these compatibility issues will help alleviate the issue.

Doesn't look like the changes have stopped the issue

```
│ Error saving state: failed to upload state: operation error S3: PutObject,
│ https response error StatusCode: 501, RequestID: , HostID: , api error
│ NotImplemented: STREAMING-UNSIGNED-PAYLOAD-TRAILER not implemented
```

Version 1.6.5

**Comment by ILLISIS** [comment]
I am also keen to see a resolution on this

**Comment by elasticdotventures** [comment]
+1 for resolution

**Comment by missinglink** [comment]
I was able to use a Cloudflare R2 bucket as a s3 backend with terraform `1.6.6` today.

In order to solve the `NotImplemented: STREAMING-UNSIGNED-PAYLOAD-TRAILER` error I needed to add `skip_s3_checksum = true`:

```terraform
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }

  backend "s3" {
    bucket = "terraform-state"
    key    = "project_name/terraform.tfstate"
    endpoints = { s3 = "https://xxxxx.r2.cloudflarestorage.com" }
    region = "us-east-1"

    access_key = "xxxx"
    secret_key = "xxxxx"
    skip_credentials_validation = true
    skip_region_validation = true
    skip_requesting_account_id  = true
    skip_metadata_api_check     = true
    skip_s3_checksum = true
  }
}
```

**Comment by missinglink** [comment]
reference: https://github.com/hashicorp/terraform/pull/34127

**Comment by ILLISIS** [comment]
> I was able to use a Cloudflare R2 bucket as a s3 backend with terraform `1.6.6` today.
> 
> In order to solve the `NotImplemented: STREAMING-UNSIGNED-PAYLOAD-TRAILER` error I needed to add `skip_s3_checksum = true`:
> 
> ```terraform
> terraform {
>   required_providers {
>     cloudflare = {
>       source  = "cloudflare/cloudflare"
>       version = "~> 4.0"
>     }
>   }
> 
>   backend "s3" {
>     bucket = "terraform-state"
>     key    = "project_name/terraform.tfstate"
>     endpoints = { s3 = "https://xxxxx.r2.cloudflarestorage.com" }
>     region = "us-east-1"
> 
>     access_key = "xxxx"
>     secret_key = "xxxxx"
>     skip_credentials_validation = true
>     skip_region_validation = true
>     skip_requesting_account_id  = true
>     skip_metadata_api_check     = true
>     skip_s3_checksum = true
>   }
> }
> ```

Thanks! that has worked for me on v1.6.5. I have been able to init, plan and apply.

**Comment by alecaugh** [comment]
[terraform version 1.6.6]
Unfortunately this workaround doesn't seem to work when wanting to provide the key via environmental variables i.e.

```
terraform {
  required_version = "1.6.6"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4"
    }
  }
}

data "terraform_remote_state" "state" {
  backend = "s3"

  config = {
    bucket    = "terraform-state"
    key       = "project_name/terraform.tfstate"
    endpoints = { s3 = "https://xxxx.r2.cloudflarestorage.com" }
    region    = "us-east-1"

    access_key                  = "${var.CLOUDFLARE_S3_ACCESS_KEY_ID}"
    secret_key                  = "${var.CLOUDFLARE_S3_SECRET_ACCESS_KEY}"
    skip_credentials_validation = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_metadata_api_check     = true
    skip_s3_checksum            = true
  }
}
```

It's returning this as an error during the `terraform plan`:

```
 Error: Unable to access object "terraform.tfstate" in S3 bucket "terraform": operation error S3: HeadObject, https response error StatusCode: 400, RequestID: , HostID: , api error BadRequest: Bad Request
│```

Has anyone else encountered this issue and found a solution?

**Comment by missinglink** [comment]
> doesn't seem to work when wanting to provide the key via environmental variables

https://stackoverflow.com/a/59491777

**Comment by alecaugh** [comment]
@missinglink It's not an issue with using the values from environment variables, it is successfuly authenticating to the S3 API.
There's an issue where the `HeadObject` API call in the terraform plan doesn't succeed. 
Sometimes the above error isn't thrown, as if the remote state file has been fetched but it has no content. All of the resources need to be created in the plan results even though they exist and are present in the state file.

**Comment by alecaugh** [comment]
Fixed my issue. I misunderstood what the `terraform_remote_state` did. 
What I needed was this solution https://github.com/hashicorp/terraform/issues/13022#issuecomment-294262392

**Comment by crw** [comment]
I am under the impression that as of the 1.6.6 release, the original issue scenario now is supported or have work-arounds. Is anyone still experiencing the original issue as described? If not I'll close this issue. Thanks!

**Comment by missinglink** [comment]
@crw it certainly doesn't work 'out of the box' as there is significant configuration required.

Once this issue is closed where will the knowledge gained in this thread live?

**Comment by crw** [comment]
Good question. I doubt we would document the nuances of configuration for every 3rd party S3-compatible vendor on the primary S3 backend page. Is there any existing documentation on this on the Cloudflare side? A quick google search turns up this user-editable page: https://developers.cloudflare.com/r2/examples/terraform/ -- my gut feeling is that this would be the best place for this documentation.

**Comment by 25thhour** [comment]
Following confirmed to work on Terraform `v1.7.4`
```
  backend "s3" {
    bucket = "whatever"
    key    = "key/goes/here/terraform.tfstate"

    region                      = "auto"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
    use_path_style              = true
    # endpoint                  = AWS_ENDPOINT_URL_S3

    /*
      ENVIRONMENT VARIABLES
      ---------------------
      AWS_ACCESS_KEY_ID     - R2 token
      AWS_SECRET_ACCESS_KEY - R2 secret
      AWS_ENDPOINT_URL_S3   - R2 location: https://ACCOUNT_ID.r2.cloudflarestorage.com
    */
  }

**Comment by simonostendorf** [comment]
@jwdeane 
> Following confirmed to work on Terraform `v1.7.4`

You're missing state lock here, correct?

Is there a way to enable r2 to support state locking.

**Comment by crw** [comment]
Closing this comment. For future viewers, the suggested path forward is to edit the page mentioned in  https://github.com/hashicorp/terraform/issues/33847#issuecomment-1877587055, possibly using the information provided in https://github.com/hashicorp/terraform/issues/33847#issuecomment-1974231305. Thanks!
