### ISSUE TITLE
Setting a map variable in tfvar file via dotted notation failing

### ISSUE THREAD

**Issue by ascendantlogic** [hashicorp/terraform#4023]
I just pulled and compiled the latest code [as of this commit](https://github.com/hashicorp/terraform/commit/7e0cbb4da7bc031b66cb3fe02d906acc7a0c2241). Now when I attempt to do a plan I get the following error:

```
 ~  workspace  infrastructure  terraform  create_api_chef +  $  terraform plan -var-file aws-creds.tfvars -var-file values.tfvars
invalid value "values.tfvars" for flag -var-file: Error parsing values.tfvars: At 33:10: expected: IDENT | STRING | ASSIGN | LBRACE got: PERIOD
```

My variable declarations are as follows:
```
# SSH keys
variable "prod_keys" { default = {} }
variable "dev_keys" { default = {} }
variable "monitor_keys" { default = {} }
```

And the line in question in my `values.tfvars` file is:
```
prod_keys.us-west-2 = "ssh-key-value-goes-here"
```

This was working as of a dev 0.6.7 build from a few weeks ago, but I don't know what commit I had last checked out otherwise I'd bisect it myself.

**Comment by ascendantlogic** [comment]
I have put the values directly in the variable declarations as a workaround for the time being.

**Comment by jen20** [comment]
@ascendantlogic I'm wondering whether the HCL parser replacement had anything to do with this - it seems one of the most likely candidates if this was previously working. I'll try to reproduce and see what I can find.

**Comment by jen20** [comment]
Looking at the error message this is definitely an HCL parser regression. I suspect dot-notation map support is simply missing from the new parser and there was no test coverage, which we also need to rectify.

**Comment by jen20** [comment]
I think https://github.com/hashicorp/hcl/pull/65 should fix this, but we still need to increase the test coverage in Terraform as well as in HCL. @ascendantlogic are you able to verify by building from `master` (with a `make updatedeps`)?

**Comment by ascendantlogic** [comment]
@jen20 pulled latest master and it seems to be fine now. I can run a `terraform plan` without error.

:metal:

**Comment by ashmere** [comment]
Just built from master using vagrantfile and retried the maps are still not being overriden

**Comment by phinze** [comment]
Hi @ashmere, are you still seeing this problem with 0.6.8? If so, can you provide steps to reproduce so we can take a look? Thanks!

**Comment by ketzacoatl** [comment]
Confirmed here too - fails with 0.6.7, but works in 0.6.8!

**Comment by ashmere** [comment]
Great news sorry I haven't had a chance to recheck

**Comment by phinze** [comment]
Closing as fixed in 0.6.8!
