### ISSUE TITLE
Cannot apply http"s" health check to Target Pool

### ISSUE THREAD

**Issue by phanect** [hashicorp/terraform#4282]
I tried to use google_compute_https_health_check as follows:

``` json5
    google_compute_https_health_check: {
      app: {
        name: "app-health-check",
        // ...
      }
    },

    google_compute_target_pool: {
      app: {
        // ...
        health_checks: [ "${ google_compute_https_health_check.app.name }" ]
      }
    },
    // ...
```

However, I added it into google_compute_target_pool and following error occurs:

``` shell
* google_compute_target_pool.app: Error reading HealthCheck: googleapi: Error 404: The resource 'projects/appcrm/global/httpHealthChecks/app-health-check' was not found, notFound
```

According to error message, `google_compute_target_pool.[appname].health_checks` uses API for HTTP health check.
I looked around the doc and didn't find equivalent arguments, so it looks a bug.

Terraform version: v0.6.8
Platform: Kubuntu 14.04

Full example:

``` json
{
    "provider": {
        "google": {
            "credentials": "${ file(\"google.json\") }",
            "project": "appcrm",
            "region": "asia-east1"
        }
    },
    "resource": {
        "google_compute_instance": {
            "app": {
                "name": "appserver",
                "machine_type": "f1-micro",
                "zone": "asia-east1-b",
                "disk": {
                    "image": "app",
                    "type": "pd-ssd"
                },
                "network_interface": {
                    "network": "app",
                    "access_config": {}
                },
                "service_account": {
                    "scopes": [
                        "https://www.googleapis.com/auth/compute.readonly"
                    ]
                }
            }
        },
        "google_compute_network": {
          "app": {
            "name":       "app",
            "ipv4_range": "10.240.0.0/16"
          }
        },
        "google_compute_address": {
            "app_lb": {
                "name": "app-lb"
            }
        },
        "google_compute_https_health_check": {
            "app": {
                "name": "app-health-check",
                "request_path": "/img/favicon.ico",
                "check_interval_sec": 3,
                "timeout_sec": 3,
                "healthy_threshold": 2,
                "unhealthy_threshold": 1
            }
        },
        "google_compute_target_pool": {
            "app": {
                "name": "app",
                "instances": [
                    "${ google_compute_instance.app.*.self_link }"
                ],
                "health_checks": [
                    "${ google_compute_https_health_check.app.name }"
                ]
            }
        },
        "google_compute_forwarding_rule": {
            "app": {
                "name": "app",
                "target": "${ google_compute_target_pool.app.self_link }",
                "ip_address": "${ google_compute_address.app_lb.self_link }"
            }
        }
    }
}
```

**Comment by lwander** [comment]
@phanect, looks like only HTTP health checks are supported [right now](https://cloud.google.com/sdk/gcloud/reference/compute/target-pools/add-health-checks). Also, you need to refer to your instances in the target pool by `self_link` rather than `name`.

**Comment by phanect** [comment]
> looks like only HTTP health checks are supported right now.
Hmm, then you have to wait for Google to implement API.

> Also, you need to refer to your instances in the target pool by self_link rather than name.
Oh, yes. I fixed above code.

**Comment by lwander** [comment]
@phanect,

> Hmm, then you have to wait for Google to implement API.

Yes, unfortunately. I'll leave this issue open as a reminder to implement this once it's available.

**Comment by psychonaut** [comment]
ping, according to terraform docs https checks are implemented but problem still occurs:

* google_compute_target_pool.kibana-443-eu: Error reading HealthCheck: googleapi: Error 404: The resource 'projects/heka-elastic-kibana/global/httpHealthChecks/https-check' was not found, notFound

**Comment by ryan-loanpal** [comment]
According to Google Compute API docs, httpsHealthCheck is supported, but it looks like this is still missing in the current Terraform 0.7.9 release.

https://cloud.google.com/compute/docs/reference/latest/#HttpsHealthChecks

**Comment by triggerants** [comment]
+1

**Comment by denibertovic** [comment]
This is till an issue. I can add https health check but when I try to tie them to a target pool I get an error.

**Comment by z1nkum** [comment]
I have the same problem - can't use https health-checks via terraform
From Google side: https://cloud.google.com/compute/docs/reference/latest/httpsHealthChecks

**Comment by mschroeder223** [comment]
If you look at the docs for [adding health checks to TargetPools](https://cloud.google.com/compute/docs/reference/latest/targetPools/addHealthCheck) you'll see that Google's api only allows you to add http health checks. This isn't a Terraform issue.

**Comment by z1nkum** [comment]
@mschroeder223 Sorry, my fault. I've try to use https checks via Google Cloud console and realized that there is no such option.
