### ISSUE TITLE
Terraform crash - reporting as instructed by the crash

### ISSUE THREAD

**Issue by ellucianBret** [hashicorp/terraform#5338]
The console output seems to indicate that it crashed on a syntax error while parsing "${var.apply_immediately}"

Attached is the console output and the crash log

[crash.log.txt](https://github.com/hashicorp/terraform/files/147716/crash.log.txt)
[console.txt](https://github.com/hashicorp/terraform/files/147718/console.txt)

**Comment by jen20** [comment]
Relevant log section:

```
panic: Error reading level config: strconv.ParseBool: parsing "${apply_immediately}": invalid syntax
2016/02/26 05:32:59 [DEBUG] terraform-provider-aws: 
2016/02/26 05:32:59 [DEBUG] terraform-provider-aws: goroutine 134 [running]:
2016/02/26 05:32:59 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc820479f80, 0xc8201c6820, 0x1, 0x1, 0xc8201c6802, 0x0, 0x0, 0x0, 0x0, 0x1490000, ...)
2016/02/26 05:32:59 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:385 +0x20a
2016/02/26 05:32:59 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc820479f80, 0x12be470, 0x11, 0x1201, 0x0, 0x0, 0x0, 0x0, 0xc820540000, 0x0, ...)
2016/02/26 05:32:59 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:356 +0x235
2016/02/26 05:32:59 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc820479f80, 0x12be470, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/02/26 05:32:59 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:333 +0x78
2016/02/26 05:32:59 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.schemaMap.diffString(0xc8205615c0, 0x12be470, 0x11, 0xc8201a95f0, 0xc8203b2e70, 0xc820479f80, 0x0, 0x0, 0x0)
2016/02/26 05:32:59 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:919 +0xa5
2016/02/26 05:32:59 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc8205615c0, 0x12be470, 0x11, 0xc8201a95f0, 0xc8203b2e70, 0xc820479f80, 0x0, 0x0, 0x0)
2016/02/26 05:32:59 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/schema.go:566 +0xaf
```

**Comment by ellucianBret** [comment]
the crash was triggered by some invalid syntax, but it was a crash!

**Comment by iverberk** [comment]
I experienced a similar crash when I inadvertently assigned a string to the self parameter in the aws_security_group resource: 

2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: panic: Error reading level config: strconv.ParseBool: parsing "8090": invalid syntax
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: goroutine 265 [running]:
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: panic(0xd95b00, 0xc820243970)
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:     /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc820430060, 0xc820548030, 0x1, 0x1, 0xc820548002, 0x0, 0x0, 0x0, 0x0, 0xc820510000, ...)
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:     /private/tmp/terraform20160322-40204-nd0o52/terraform-0.6.14/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:394 +0x20a
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ResourceData).getChange(0xc820430060, 0x109b0f0, 0x7, 0x1201, 0x0, 0x0, 0x0, 0x0, 0x13c0000, 0x0, ...)
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:     /private/tmp/terraform20160322-40204-nd0o52/terraform-0.6.14/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:365 +0x235
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ResourceData).diffChange(0xc820430060, 0x109b0f0, 0x7, 0x0, 0x0, 0x0, 0x0, 0xc820191168)
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:     /private/tmp/terraform20160322-40204-nd0o52/terraform-0.6.14/src/github.com/hashicorp/terraform/helper/schema/resource_data.go:342 +0x78
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.schemaMap.diffSet(0xc820221b90, 0x109b0f0, 0x7, 0xc82055d6c0, 0xc820548010, 0xc820430060, 0x0, 0x0, 0x0)
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:     /private/tmp/terraform20160322-40204-nd0o52/terraform-0.6.14/src/github.com/hashicorp/terraform/helper/schema/schema.go:808 +0x7c
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.schemaMap.diff(0xc820221b90, 0x109b0f0, 0x7, 0xc82055d6c0, 0xc820548010, 0xc820430060, 0x8fba00, 0x0, 0x0)
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:     /private/tmp/terraform20160322-40204-nd0o52/terraform-0.6.14/src/github.com/hashicorp/terraform/helper/schema/schema.go:582 +0x32e
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc820221b90, 0xc820198090, 0xc820198570, 0xc8201c8950, 0x0, 0x0)
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:     /private/tmp/terraform20160322-40204-nd0o52/terraform-0.6.14/src/github.com/hashicorp/terraform/helper/schema/schema.go:302 +0x1ff
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc82033ecc0, 0xc820198090, 0xc820198570, 0x12, 0x0, 0x0)
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:     /private/tmp/terraform20160322-40204-nd0o52/terraform-0.6.14/src/github.com/hashicorp/terraform/helper/schema/resource.go:163 +0x44
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc8202741e0, 0xc8202e0000, 0xc820198090, 0xc820198570, 0xc8204c5801, 0x0, 0x0)
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:     /private/tmp/terraform20160322-40204-nd0o52/terraform-0.6.14/src/github.com/hashicorp/terraform/helper/schema/provider.go:175 +0x1c5
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Diff(0xc8203275c0, 0xc8202440a0, 0xc820543730, 0x0, 0x0)
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:     /private/tmp/terraform20160322-40204-nd0o52/terraform-0.6.14/src/github.com/hashicorp/terraform/rpc/resource_provider.go:334 +0x76
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: reflect.Value.call(0xd0ed80, 0xfe7bb8, 0x13, 0x10955f8, 0x4, 0xc8205a9ed8, 0x3, 0x3, 0x0, 0x0, ...)
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:     /usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:435 +0x120d
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: reflect.Value.Call(0xd0ed80, 0xfe7bb8, 0x13, 0xc8205a9ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:     /usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:303 +0xb1
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: net/rpc.(*service).call(0xc82033fa80, 0xc82033f8c0, 0xc820349620, 0xc82042db80, 0xc8203275e0, 0xab9f00, 0xc8202440a0, 0x16, 0xab9f60, 0xc820543730, ...)
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:     /usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:383 +0x1c2
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws: created by net/rpc.(*Server).ServeCodec
2016/03/31 11:18:35 [DEBUG] terraform-provider-aws:     /usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:477 +0x49d

**Comment by mitchellh** [comment]
Does anyone have a config that can reproduce this? I have a hunch this is fixed on master since I can't repro it but w/o a known case where it was failing before I can't be 100% sure.

**Comment by ApsOps** [comment]
@mitchellh Hi. I just tried with `v0.7.3` and it still crashes. Please refer https://github.com/hashicorp/terraform/issues/7025 for config to test plus more details.

**Comment by sl1pm4t** [comment]
@mitchellh, @jen20  - looks to me like the the problem is Terraform doesn't attempt to interpolate bool attribute values.
Hence the panic when terraform tries to `strconv.ParseBool` the un-interpolated string.

This is demonstrated by the following config:
```hcl
variable "bool_lookup" {
  type = "map"
  default = {
    "0" = false
    "1" = true
  }
}

data "template_cloudinit_config" "config" {
  count = 2
  // the following will crash terraform
  base64_encode          = "${ lookup(var.bool_lookup, count.index, true) }"

  part {
    content_type = "text/x-shellscript"
    content      = "ffbaz"
  }
}
```

[console output](https://gist.github.com/sl1pm4t/380c014c0765dbedbac199d407d0e443#file-terraform-interpolated-bool-panic)
[crash.log](https://gist.github.com/sl1pm4t/380c014c0765dbedbac199d407d0e443#file-crash-log)

Also, in the original reported problem, the variable reference was missing `var.` prefix so it should have failed when Terraform attempted to interpolate the value.

**Comment by sl1pm4t** [comment]
I take it back.... the above config works with the following change:
```hcl
# BEFORE
base64_encode          = "${ lookup(var.bool_lookup, count.index, true) }"
# AFTER
base64_encode          = "${ lookup(var.bool_lookup, count.index, "true") }"
```

**Comment by mitchellh** [comment]
The referenced PR contains a fix for this issue, experienced by @sl1pm4t.

This is actually part of a larger bug (that includes necessary BC breaking changes) that we'll be releasing fixes to as part of Terraform 0.8.0, as noted in the PR itself.
