### ISSUE TITLE
Crash while refreshing state - 0.6.12

### ISSUE THREAD

**Issue by steveh** [hashicorp/terraform#5536]
Crash log attached with identifying details replaced.

`2016/03/10 09:16:44 [DEBUG] terraform-provider-aws: panic: runtime error: invalid memory address or nil pointer dereference`

[crash.log.zip](https://github.com/hashicorp/terraform/files/166015/crash.log.zip)

**Comment by jen20** [comment]
Relevant error logs.

```
2016/03/10 09:16:44 [DEBUG] terraform-provider-aws: panic: runtime error: invalid memory address or nil pointer dereference
2016/03/10 09:16:44 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x21feb6]
2016/03/10 09:16:44 [DEBUG] terraform-provider-aws:
2016/03/10 09:16:44 [DEBUG] terraform-provider-aws: goroutine 2236 [running]:
2016/03/10 09:16:44 [DEBUG] terraform-provider-aws: panic(0xcea400, 0xc82000a140)
2016/03/10 09:16:44 [DEBUG] terraform-provider-aws: 	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
2016/03/10 09:16:44 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.flattenLambdaVpcConfigResponse(0xc826340500, 0x0, 0x0, 0x0)
2016/03/10 09:16:44 [DEBUG] terraform-provider-aws: 	/private/tmp/terraform20160227-37732-w3ykp1/terraform-0.6.12/src/github.com/hashicorp/terraform/builtin/providers/aws/structure.go:693 +0x336
2016/03/10 09:16:44 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsLambdaFunctionRead(0xc8260faae0, 0xa0c360, 0xc822f72300, 0x0, 0x0)
2016/03/10 09:16:44 [DEBUG] terraform-provider-aws: 	/private/tmp/terraform20160227-37732-w3ykp1/terraform-0.6.12/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_lambda_function.go:260 +0x596
2016/03/10 09:16:44 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc822b8d180, 0xc8260fc000, 0xa0c360, 0xc822f72300, 0xc822ca4460, 0x0, 0x0)
```

**Comment by phinze** [comment]
Fixed in #5182, which has landed in master and will come out with the next release! (Planned for early next week)

**Comment by steveh** [comment]
I just built the master branch but unfortunately it still crashes, albeit in what looks like a different file, so maybe a different bug:

```
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws: panic: runtime error: invalid memory address or nil pointer dereference
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x193b83]
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws: 
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws: goroutine 857 [running]:
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws: panic(0xdbef00, 0xc82000a140)
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws:   /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsLambdaPermissionCreate(0xc823d4e5a0, 0xaab5c0, 0xc821a12b40, 0x0, 0x0)
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws:   /Users/steve/go/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_lambda_permission.go:124 +0xa13
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc82190f1c0, 0xc823d4b380, 0xc823d7c840, 0xaab5c0, 0xc821a12b40, 0xc823d4b401, 0x0, 0x0)
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws:   /Users/steve/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:146 +0x29e
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc821a6b200, 0xc823b16f80, 0xc823d4b380, 0xc823d7c840, 0xc823d54001, 0x0, 0x0)
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws:   /Users/steve/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:162 +0x1ed
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Apply(0xc821520120, 0xc823b141a0, 0xc823d7c8f0, 0x0, 0x0)
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws:   /Users/steve/go/src/github.com/hashicorp/terraform/rpc/resource_provider.go:323 +0x76
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws: reflect.Value.call(0xcffa40, 0xfd6f38, 0x13, 0x1083bb0, 0x4, 0xc823a7fed8, 0x3, 0x3, 0x0, 0x0, ...)
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws:   /usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:435 +0x120d
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws: reflect.Value.Call(0xcffa40, 0xfd6f38, 0x13, 0xc823a7fed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws:   /usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:303 +0xb1
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws: net/rpc.(*service).call(0xc8217beb40, 0xc8217beb00, 0xc8218c8dd0, 0xc820670f00, 0xc821520140, 0xaac4c0, 0xc823b141a0, 0x16, 0xaac520, 0xc823d7c8f0, ...)
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws:   /usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:383 +0x1c2
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws: created by net/rpc.(*Server).ServeCodec
2016/03/15 09:05:27 [DEBUG] terraform-provider-aws:   /usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:477 +0x49d
```

**Comment by phinze** [comment]
Thanks for trying it out @steveh - based on the [line of code where it crashes](https://github.com/hashicorp/terraform/blob/a1f77891611f47ad0c561d16a67007f4419a2358/builtin/providers/aws/resource_aws_lambda_permission.go#L124), looks like it's possible for AWS to return a successful response with no statement attached. :neutral_face: 

Reopening and we'll get an extra guard in there! :+1:

**Comment by dtolnay** [comment]
This was probably caused by #7448.
