### ISSUE TITLE
Cannot destroy aws_rds_cluster, unexpected state

### ISSUE THREAD

**Issue by jescochu** [hashicorp/terraform#5753]
Running version 0.6.13 (problem also existed in 0.6.12)

Whenever I run a destroy on a plan that has deployed an Aurora cluster, it is able to remove the individual cluster instances, but not the cluster resource itself. It always fails with this error:

> 1 error(s) occurred:
> 
> * aws_rds_cluster.ahs_db_cluster: [WARN] Error deleting RDS Cluster (easoopsdev-ahs-cluster): unexpected state 'available', wanted target '[destroyed]'
> 

I am not doing anything too strange with my resource:

```
resource "aws_rds_cluster" "ahs_db_cluster" {
	cluster_identifier = "${var.environment}-ahs-cluster"
	availability_zones = [ "${split(",", var.availability_zones)}" ]
	database_name = "ah_${var.environment}_s_core"
	master_username = "root"
	master_password = "change_me"
	backup_retention_period = 30
	preferred_backup_window = "11:15-12:15"
	vpc_security_group_ids = [ "${aws_security_group.ahs_db.id}" ]
	db_subnet_group_name = "default-vpc-aed899c6"
	final_snapshot_identifier = "${var.environment}-ahs-app-final-ss"
}
```
From there, I create two rds_cluster_instances, but they are destroyed just fine.

When this error happens, I have to remove the cluster with the aws-cli tool then run destroy again so it finishes cleaning up the rest of the deployment. I noticed when I use the CLI, there is a bit of a delay while the cluster's state goes from "available" to "deleting". However, even after the Terraform run, it is still "available" so it is like a delete isn't being triggered.

The only thing I am doing slightly out of the ordinary is running a script after the fact to register my Aurora cluster endpoint as a service in Consul (until the Consul provider allows for this behavior natively):

```
resource "null_resource" "cluster_registration" {
	provisioner "local-exec" {
        command = "python ../scripts/register_service.py -n ${aws_rds_cluster.ahs_db_cluster.endpoint} -i ${aws_rds_cluster.ahs_db_cluster.endpoint} -p ${aws_rds_cluster.ahs_db_cluster.port} -s db_master -t ahs_app_${var.environment}_sd"
    }
}
```
Originally I had this as a provisioner within the cluster resource itself, but moved it out to a null resource to see if it would fix the error. Both ways produce the same results. I wouldn't think that a local-exec call would have anything to do with the resource's destruction though.

**Comment by catsby** [comment]
Hey @jescochu – I _believe_ this is fixed in v0.6.14. I can't reproduce it locally, using this config:

```hcl
resource "aws_rds_cluster" "default" {
  cluster_identifier = "tf-aurora-cluster-test"
  availability_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]
  database_name      = "mydb"
  master_username    = "foo"
  master_password    = "mustbeeightcharaters"
}

resource "aws_rds_cluster_instance" "cluster_instances" {
  identifier         = "tf-cluster-instance"
  cluster_identifier = "${aws_rds_cluster.default.id}"
  instance_class     = "db.r3.large"
}
```

Any chance you can try upgrading? 

The local exec _shouldn't_ do anything to harm you there... it shouldn't be adjusting the graph so there should not be any extra dependency introduced.

**Comment by jescochu** [comment]
Hi @catsby, thanks for looking into this.

The problem persists, however I have more information and I am no longer convinced this is a bug, but rather a misunderstanding of how the _final_snapshot_identifier_ attribute is used. Before, we set a snapshot ID and would freely deploy and redeploy without changing this ID. We saw that when it was set, we would not see data loss on redeploys of Aurora clusters. Now, however, I am getting an error when trying to destroy because it is saying the final DB snapshot I'm specifying already exists:

```
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws: 2016/04/01 21:45:24 [DEBUG] [aws-sdk-go] DEBUG: Response rds/DeleteDBCluster Details:
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws: ---[ RESPONSE ]--------------------------------------
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws: HTTP/1.1 400 Bad Request
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws: Content-Length: 371
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws: Content-Type: text/xml
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws: Date: Fri, 01 Apr 2016 21:45:23 GMT
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws: X-Amzn-Requestid: 0a5eff1d-f853-11e5-a719-7bbb79a9abd0
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws:
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws: <ErrorResponse xmlns="http://rds.amazonaws.com/doc/2014-10-31/">
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws:   <Error>
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws:     <Type>Sender</Type>
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws:     <Code>DBClusterSnapshotAlreadyExistsFault</Code>
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws:     <Message>Cannot create the cluster snapshot because one with the identifier engineload-db-final-ss already exists.</Message>
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws:   </Error>
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws:   <RequestId>0a5eff1d-f853-11e5-a719-7bbb79a9abd0</RequestId>
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws: </ErrorResponse>
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws:
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws: -----------------------------------------------------
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws: 2016/04/01 21:45:24 [DEBUG] Waiting for state to become: [destroyed]
2016/04/01 21:45:24 [DEBUG] terraform-provider-aws: 2016/04/01 21:45:24 [TRACE] Waiting 3s before next try
```

But I fully expect it to exist. I want it to overwrite the one it already created. Am I not using this correctly?

Here is my aws_rds_cluster resource producing this log output:

```
resource "aws_rds_cluster" "ahs_db_cluster" {
	cluster_identifier = "${var.environment}-ahs-cluster"
	availability_zones = [ "${split(",", var.availability_zones)}" ]
	database_name = "ah_${var.environment}_s_core"
	master_username = "engine_app"
	master_password = "change_me"
	backup_retention_period = 30
	preferred_backup_window = "11:15-12:15"
	vpc_security_group_ids = [ "${aws_security_group.ahs_db.id}" ]
	db_subnet_group_name = "default-vpc-aed899c6"
    final_snapshot_identifier = "${var.environment}-db-final-ss"
}
```
Am I expected to change the identifier of the snapshot every time? I am certain we have deployed, destroyed, and redeployed numerous environments without changing the actual value of that attribute.

**Comment by catsby** [comment]
Hey @jescochu – yes at this time it is expected that you change `final_snapshot_identifier`. Terraform does not assume you'd like to replace that every time, and in leu of offering yet another config option to overwrite it, we instead just insist you rename it if you do not want an error. 

Sorry for the trouble!
