### ISSUE TITLE
AWS Opsworks Rails App Layer ignores manage_bundler

### ISSUE THREAD

**Issue by ldhertert** [hashicorp/terraform#5907]
Any rails app later created by terraform has "Install and manage Bundler" set to "no", regardless of the value placed in the terraform config.  Using terraform v0.6.14.

**Comment by apparentlymart** [comment]
Thanks for reporting this, @ldhertert.

I did some initial investigation here but didn't have time yet to dig deep. The rest of this comment is just some notes for future-me or anyone else that wants to try to debug this:

The opsworks layer attributes are implemented in a generic, schema-driven way so I think there are two obvious ways in which this could be broken:

* The attribute name Terraform is using in the underlying API call is incorrect. This would mean it would affect only this attribute on this layer type.
* The way Terraform is serializing boolean values is incorrect. This would mean that all of the boolean attributes could be broken across all layer types, which seems less likely since I remember seeing other booleans work during my earlier testing.

[The documentation](http://docs.aws.amazon.com/opsworks/latest/APIReference/API_CreateLayer.html) shows that there is indeed an attribute called `ManageBundler`, which is the name that Terraform is using.

As far as I can tell there is no real documentation for what values are expected for each attribute, so the values used by Terraform were figured out by trying things in the UI and then checking how they appeared in the API responses. However, it's possible that there are some inconsistencies in these that I didn't catch in the original implementation work.

When I get a chance I'll try to repro this and see how what Terraform is writing is different to what the AWS console writes when populating this attribute.

**Comment by janschumann** [comment]
I think I found a similar bug while testing #4419 (opsworks app). There some optional arguments can be passed to the aws api depending on the application type. These are passed as `Arguments` of type `map[string]*string`. Probably these two bugs share the same source of pain?

**Comment by u2mejc** [comment]
I poked at this a little today. First issue is here in opsworks_layers.go

```go
var (
   opsworksTrueString  = "1"
   opsworksFalseString = "0"
)
```
Should be:
```go
var (
   opsworksTrueString  = "true"
   opsworksFalseString = "false"
)
```

That small change actually resolves @ldhertert initial issue. If you `terraform apply`, it works. But after digging, the root issue is the live (remote AWS) layer attributes are not being written to the statefile. This breaks changing anything inside the attributes map and then the eval loop fails to see any changes. I poked around some, but it didn't bubble up to me yet. I'll poke at it more as time allows, but I don't have a patch staged at this time.

**Comment by iroller** [comment]
Stuck on the same issue with `manage_bundler` here

**Comment by stack72** [comment]
This is fixed via #7219

**Comment by u2mejc** [comment]
@stack72 That close may be a little premature... Did you see why I didn't take credit for a two line PR previously (above)?

**Comment by u2mejc** [comment]
@stack72 Please reopen this, my code that dlanner created the PR for doesn't fix this issue.

**Comment by stack72** [comment]
Reopened on request :)

**Comment by u2mejc** [comment]
Thx! 🍻

**Comment by stack72** [comment]
@janschumann if that PR will close this PR then I would love that :)

**Comment by stack72** [comment]
Verified that this works via #10669
