### ISSUE TITLE
Failed Idempotency with AWS Security Group on Instance With Multiple ENIs

### ISSUE THREAD

**Issue by Andy--Rose** [hashicorp/terraform#7635]
RELATES TO https://github.com/hashicorp/terraform/issues/2998

I am trying to create a LB instance with 3 ENIs attached, one for each Subnet in the environment. 

The first half of this issue is outlined in issue #2998, which does not allow you to define the default ENI for an instance. I worked around this by allowing the instance to create the default ENI and attaching the EIP I needed to the instance.

The second half of this issue came when trying to create a new Security Group for the instance. When I tried to attach the SG to the instance, I got the following error:

```
Error applying plan:

1 error(s) occurred:

* aws_instance.netscaler: InvalidInstanceID: There are multiple interfaces attached to instance 'i-062a9ba9'. Please specify an interface ID for the operation instead.
    status code: 400, request id: b11dbd18-64b6-4e24-9711-a3d41b025448
```

I **would** use the interface ID to attach the SG, but unfortunately I would need to attach it to the ENI which I was unable to create manually. There is no way to get the ID for that ENI because it is not provided in the exported attributes after creating the EC2 instance.

My only option now is to destroy the environment and rebuild it with the change. Further changes to security groups will suffer the same problem.
### Terraform Version

0.6.16
### Affected Resource(s)

Please list the resources as a list, for example:
- aws_instance
- aws_security_group
- aws_network_interface
### Terraform Configuration Files

``` hcl
###REMOVED SUBNET CONFIG FOR BREVITY###
# Netscaler EIPs for the public and management subnets
resource "aws_eip" "netscaler_management_eni_eip" {
  count = "${length(split(",", lookup(var.azs, var.region)))}"
  vpc   = true
}

resource "aws_eip" "netscaler_public_eni_eip" {
  count = "${length(split(",", lookup(var.azs, var.region)))}"
  vpc   = true
}

# Netscaler ENI for public subnets
resource "aws_network_interface" "netscaler_public_eni" {
  count             = "${length(split(",", lookup(var.azs, var.region)))}"
  subnet_id         = "${element(aws_subnet.fabric_public_subnet.*.id, count.index)}"
  description       = "Netscaler ENI for Public subnet"
  security_groups   = ["${aws_security_group.netscaler_public_sg.id}"]
  source_dest_check = false
  attachment {
    instance = "${element(aws_instance.netscaler.*.id, count.index)}"
    device_index = 1
  }
}

# A Private ENI needs to be added for every private subnet * Every LB
resource "aws_network_interface" "netscaler_private_eni" {
  count             = "${length(split(",", lookup(var.azs, var.region))) * length(split(",", lookup(var.azs, var.region)))}"
  subnet_id         = "${element(aws_subnet.fabric_subnet.*.id, count.index - ((count.index / length(aws_subnet.fabric_subnet.*.id)) * length(aws_subnet.fabric_subnet.*.id)))}"
  description       = "Netscaler ENI for Private subnet"
  security_groups   = ["${aws_security_group.netscaler_private_sg.id}"]
  source_dest_check = false
  attachment {
    instance = "${element(aws_instance.netscaler.*.id, count.index - ((count.index / length(aws_subnet.fabric_subnet.*.id)) * length(aws_subnet.fabric_subnet.*.id)))}"
    device_index = "${2 + (count.index - ((count.index / length(aws_subnet.fabric_subnet.*.id)) * length(aws_subnet.fabric_subnet.*.id)))}"
  }
}

# Netscaler EIP associations for ENIs of the different subnets
resource "aws_eip_association" "netscaler_management_eni_eip_association" {
  count                 = "${length(split(",", lookup(var.azs, var.region)))}"
  #network_interface_id  = "${element(aws_network_interface.netscaler_management_eni.*.id, count.index)}"
  instance_id           = "${element(aws_instance.netscaler.*.id, count.index)}"
  allocation_id         = "${aws_eip.netscaler_management_eni_eip.id}"
}

resource "aws_eip_association" "netscaler_public_eni_eip_association" {
  count                 = "${length(split(",", lookup(var.azs, var.region)))}"
  network_interface_id  = "${element(aws_network_interface.netscaler_public_eni.*.id, count.index)}"
  allocation_id         = "${aws_eip.netscaler_public_eni_eip.id}"
}

resource "aws_security_group" "company_networks" {
  name = "${var.clustername}-companyNetworks-${var.region}-node-sg"
  description = "Connect over TCP from Company IP spaces."
  vpc_id = "${aws_vpc.fabric_vpc.id}"

  ingress {
    from_port = 0
    to_port = 65535
    protocol = "tcp"
    cidr_blocks = ["1.2.3.0/24", "4.5.6.7/32"]
  }
}

resource "aws_security_group" "netscaler_management_eip_sg" {
  name = "${var.clustername}-netscalerManagementEni-${var.region}-node-sg"
  description = "Security Group for Management subnet ENI of Netscaler"
  vpc_id = "${aws_vpc.fabric_vpc.id}"
  ingress {
    from_port = 22
    to_port = 22
    protocol = "tcp"
    security_groups = ["${aws_security_group.netscaler_management_sg.id}"]
  }
}

resource "aws_instance" "netscaler" {
    # Create 1 NS instance per AZ
    count             = "${length(split(",", lookup(var.azs, var.region)))}"

    # The connection block tells our provisioner how to
    # communicate with the resource (instance)
    connection {
        # The default username for our AMI
        user = "ubuntu"
        agent = true
        # The connection will use the local SSH agent for authentication.
    }

    instance_type = "${var.netscaler_instance_type}"

    source_dest_check = "false"

    # Lookup the correct AMI based on the region we specified
    ami = "${lookup(var.netscaler_amis, var.region)}"

    # The name of our SSH keypair we created above.
    key_name = "${aws_key_pair.auth.id}"

    # One for each management subnet
    subnet_id = "${element(aws_subnet.fabric_management_subnet.*.id, count.index)}"

    vpc_security_group_ids = [ 
        "${aws_security_group.netscaler_management_eip_sg.id}",
        "${aws_security_group.company_networks.id}"
    ]

    # Attach the role
    iam_instance_profile = "Netscaler"
    tags {
        "Name" = "${var.clustername}-fabric-netscaler-${count.index}"
    }
}
```

---
### Debug Output

https://gist.github.com/Andy--Rose/e86e8f54713ddb63576eb8e55dc8b400
### Panic Output

None
### Expected Behavior

This is expected behavior for this error. The error is very descriptive and clear. The problem is the missing piece causing this error to have no workaround.
### Actual Behavior

None
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
### Important Factoids

There is a gap here in Terraform. The AWS API allows you to define the Network Interfaces used when provisioning EC2 instances, but this is not implemented by Terraform. Not including this is causing changes related to the default ENI to be impossible, removing the idempotency from the environment.
### References

https://github.com/hashicorp/terraform/issues/2998

**Comment by grubernaut** [comment]
Fixed via #14299, thanks!

**Comment by ebarault** [comment]
@grubernaut this should be reopened: case where `source_dest_check` is changed afterwards on primary eni is not fixed, see: https://github.com/hashicorp/terraform/issues/19959

**Comment by grubernaut** [comment]
Hey @ebarault, unfortunately no longer work at HashiCorp. You'd probably need to ping @catsby or @tombuildsstuff, thanks.

**Comment by tombuildsstuff** [comment]
@ebarault thanks for letting us know - I've scheduled #19959 to be migrated to the AWS repository where someone can take a look at fixing this :)
